### ISSUE TITLE
Howto for Redux Devtools

### ISSUE THREAD

**Issue by SethDavenport** [angular-redux/ng2-redux#101]
We work great with the redux devtools bundled as  a chrome extension.

However some community members have requested a quick doc on how to use them with the sample app.

A recorded screen session might be in order.

**Comment by drager** [comment]
@SethDavenport: Dan's own screen recording might work? https://egghead.io/lessons/javascript-getting-started-with-redux-dev-tools

**Comment by zalmoxisus** [comment]
@SethDavenport, there's a [recorded screen session](https://egghead.io/lessons/javascript-getting-started-with-redux-dev-tools) by Trevor Miller. Also [I showed all the features at React Europe](https://www.youtube.com/watch?v=YU8jQ2HtqH4).

**Comment by SethDavenport** [comment]
Yeah this issue was mainly about how to hook it up to an ng2 project; but I think we've got it covered in our docs now.
