### ISSUE TITLE
invariant dependency is causing 'process is not defined' error

### ISSUE THREAD

**Issue by jkyoutsey** [angular-redux/ng2-redux#105]
I'm using SystemJS and gulp to build an Angular2 rc0 app.  Seeing this error from the invariant dependency:

`localhost/:25 Error: ReferenceError: process is not defined
	    at Object.eval (http://localhost:3001/node_modules/invariant/invariant.js:23:16)
	    at eval (http://localhost:3001/node_modules/invariant/invariant.js:55:4)
	    at eval (http://localhost:3001/node_modules/invariant/invariant.js:56:3)
	    at Object.eval (http://localhost:3001/node_modules/ng2-redux/lib/components/ng-redux.js:14:17)
	Evaluating http://localhost:3001/node_modules/invariant/invariant.js
	Evaluating http://localhost:3001/node_modules/ng2-redux/lib/components/ng-redux.js
	Evaluating http://localhost:3001/node_modules/ng2-redux/lib/components/provider.js
	Evaluating http://localhost:3001/node_modules/ng2-redux/lib/index.js`

Not sure how to satisfy this dependency.

**Comment by SethDavenport** [comment]
What version of npm and node are you using?

**Comment by SethDavenport** [comment]
Googling around suggests that this is a problem with the `invariant` library. We're not using it much, we can probably get rid of it.

**Comment by jkyoutsey** [comment]
Awesome.  I'll watch for that to close.  I'm using npm 2.14.7 and node 4.2.1 fwiw.

**Comment by bennett000** [comment]
@SethDavenport invariant should be really easy to drop, it's basically an `if` statement.  I'm hoping we can eliminate all non-angular dependencies so that our bundle is bloat-free.  

I would also really like to do an analysis of how codegen will affect us and how we can optimize for it.

**Comment by SethDavenport** [comment]
@bennett000 : yes, already got rid of it in PR #108. Just waiting for Evan to approve it and publish a new npm package version.

**Comment by bennett000** [comment]
I finally saw that.  I let my GitHub notifications get waaay out of control during  ng-conf. 

I'm really excited to look at all the awesome work you guys got done.

**Comment by SethDavenport** [comment]
@e-schultz I believe SystemJS doesn't define `process` by default unless you shim it.  Invariant assumes it's there: https://github.com/zertosh/invariant/blob/master/invariant.js#L23

Nonetheless. I agree with @bennett000 that the fewer deps we have the better; if we can replace invariant with a few lines of code I think it's worthwhile.

I updated the PR to handle the `%s` and added some unit tests.

**Comment by e-schultz** [comment]
merged in and published 2.3.2
