### ISSUE TITLE
Subscriptions not firing

### ISSUE THREAD

**Issue by nareshbhatia** [angular-redux/ng2-redux#109]
@SethDavenport, @bennett000 - as discussed at ng-Conf, I have created a slightly more complex example than the counter example supplied with ng2-redux. This one lets you enter a Github organization and displays the repositories associated with that organization. The Github project is located [here](https://github.com/archfirst/github-viewer). I have two implementations:

1. Angular2 only
2. Angular2 + ng2-redux

Unfortunately I am not able to get the ng2-redux implementation working. The actions are being dispatched correctly and the reducer is changing the state successfully. However the subscriptions are not being fired. Here's a console log of what I am seeing:

```
// This stuff is happening on app initialization
reducer - action: Object {type: "@@redux/INIT"}
reducer - curState: Object {orgName: null, errorMessage: null, repos: Array[0]}
reducer - nxtState: Object {orgName: null, errorMessage: null, repos: Array[0]}
reducer - action: Object {type: "@@redux/PROBE_UNKNOWN_ACTION_w.m.l.x.n.o.j.q.1.7.m.b.n.s.c.0.i.z.f.r"}
reducer - curState: Object {orgName: null, errorMessage: null, repos: Array[0]}
reducer - nxtState: Object {orgName: null, errorMessage: null, repos: Array[0]}
reducer - action: Object {type: "@@redux/INIT"}
reducer - curState: Object {orgName: null, errorMessage: null, repos: Array[0]}
reducer - nxtState: Object {orgName: null, errorMessage: null, repos: Array[0]}
----- orgNameSubscription -----
orgname: undefined
state.orgName: undefined
----- errorMessageSubscription -----
errorMessage: undefined
state.errorMessage: undefined
----- reposSubscription -----
repos: undefined
state.repos: undefined

// When I submit the form with orgName = "archfirst" the reducer is being called correctly
reducer - action: Object {type: "CHANGE_ORG_NAME", orgName: "archfirst"}
reducer - curState: Object {orgName: null, errorMessage: null, repos: Array[0]}
reducer - nxtState: Object {orgName: "archfirst", errorMessage: null, repos: Array[0]}

// However after this I see no call to orgNameSubscription
```

Would you be able to look at the implementation and tell me where I am going wrong? If we can get this working it would be a good second example for ng2-redux users. Thanks in advance for your time.

**Comment by e-schultz** [comment]
@nareshbhatia I'll take a look into this when I get the chance, thanks for providing the repo/implementation - it will help debug the issue.

**Comment by nareshbhatia** [comment]
I am seeing that the counter example has code to trigger change detection whenever the store changes:

    this.unsubscribe = this.ngRedux.subscribe(() => {
      this.applicationRef.tick();
    });

I don't understand the need for this because the same function has code that subscribes to the change in counter state which eventually updates the `counter` input in the `Counter` component:

    this.counter$ = this.ngRedux
        .select(state => state.counter)

This should automatically trigger change detection, so there should be no need to trigger it manually.

In any case, I added a `ngRedux.subscribe()` call to my code in order to replicate the counter example. While I still don't see my `select()` subscriptions firing, I do see this ngRedux subscription firing whenever the store changes. That doesn't help me though because it's not easy to figure out what in the store changed.

**Comment by nareshbhatia** [comment]
Thanks, @e-schultz. Also, please feel free to provide comments/feedback on my approach.

**Comment by e-schultz** [comment]
@nareshbhatia taking a quick look into things. You're right - in the ngRedux.subscribe(()=>) - there shouldn't be a need for the developer to have to worry about applicationRef.tick() - I'll try and look into the cause of that. 

For the other issues - the structure of your `AppState` is incorrect, when using `combineReducers`, the name of the reducer becomes a key in the state. 

Your `AppState` should actually be:

```js
import { Repo } from '../models/repo.model';

export class AppState {
    githubReducer: {
        orgName: string;
        errorMessage: string;
        repos: Repo[];
    }
}

 

export const initialState: AppState = {
    githubReducer: {
        orgName: null,
        errorMessage: null,
        repos:[]
    }
};
```

Then in your .select statements, you would have

```js
 this.orgNameSubscription = this.ngRedux
            .select<string>(state =>  state.githubReducer.orgName)     
// instead of 
 this.orgNameSubscription = this.ngRedux
            .select<string>(state =>  state.orgName)     

```
Submitted a PR against your repo showing the fixes - although will still need to check into the `.subscribe` needing an appref.tick()

**Comment by nareshbhatia** [comment]
@e-schultz - thanks so much for your help. I merged in your PR.

It doesn't look like `applicationRef.tick()` is really needed. I took it out and everything is working fine. I addition:

1. I fixed some issues with http error handling.
2. I now provide the initialState to the `createStore()` call. This prevents store subscribers receiving undefined values in the beginning.

Looks like the app is good to go as another example for ng2-redux!

Thanks again for your help.

**Comment by SethDavenport** [comment]
@e-schultz @nareshbhatia the ApplicationRef.tick() is needed for redux devtools to work - changes to the store from redux devtools are made outside the angular zone.

Perhaps we can change the code to only turn it on if window.devToolsExtension is truthy.

**Comment by nareshbhatia** [comment]
@SethDavenport, thanks for the clarification. FYI, I did not play with devToolsExtension because I was getting some kind of an error from TypeScript. Now that everything else is working, may be I will give it a shot.

Also to note, I hacked index.html as follows to work around Redux's need to have a global variable called `process`:

    process = {
        env: {
            NODE_ENV: 'development'
        }
    }

I think the counter example includes other dependences to keep Redux happy, whereas I decided to keep the number of dependencies to a minimum. In fact, I see that the counter example depends on React - any idea why?

**Comment by SethDavenport** [comment]
@nareshbhatia the `process` thing is likely related to #105 which should be fixed in the next patch release.

As for the react dependency in the example app, I believe this is left over from when we brought in the dev tools directly instead of using the Chrome extension. I'll remove it.

Finally, coming back to the appref.tick() - this will no longer be needed even for devtools in the upcoming 3.0 - we handle it internally.

**Comment by nareshbhatia** [comment]
Awesome! Thanks for the update.

**Comment by nareshbhatia** [comment]
I just created a more ambitious project with ng2-redux: https://github.com/sapientglobalmarkets/staffer. Also used angular-cli and angular-material2 to show how all these play well together. Would you like to link to this project in your README? It will be a great help for people ramping up on ng2-redux. As always, feedback and PRs welcome!

**Comment by ghost** [comment]
I'm not sure whether or not you've posted details in the documentation about how to structure the state when using the combineReducers function. If that is not accounted for it would be good to include that in an obvious way in usage examples. I stumbled on this article to solve a similar issue. We found it best to structure the app similar to what  @nareshbhatia was doing. The reducer as the key was the fundamental piece we missed.
