### ISSUE TITLE
How to extend counter to an object not a number

### ISSUE THREAD

**Issue by justsayno** [angular-redux/ng2-redux#116]
Sorry if I am being dense but I have extended your example into an app where I can sucessfully display the value of a part of my state if its simple number for example:

```javascript
//in my initial state
{
dashboard:0
}
```

```
// In my component 
  ngOnInit() {
    this.unsubscribe = this.ngRedux.subscribe(() => {
        this.applicationRef.tick();
    });
    this.dashboard = this.ngRedux
            .select(state => state.dashboard);
}
```

```html
 <h2>{{ dashboard | async }}</h2>
```

This works fine and I see 0 on the page. However if I make the object more complex such as:

```
const initialState = {
   dashboard:{
      currentRobot:{
        name:"Robot Name" 
      }
   }
}
```

```html
<h2>{{ dashboard.currentRobot.name | async }}</h2>
```

With the same component this doesn't work... I feel I just don't understand rxjs and I have spent the last 45 minutes trying to find an answer to how to do this and haven't had any luck.

Im so close to implementing redux in Angular2 (having done it in reactjs before) and would love some help!

**Comment by SethDavenport** [comment]
Hi @justsayno, thanks for your interest in ng2-redux!

Your suspicion is correct: Observables and async pipe don't quite work this way for nested props.

Consider: 

```typescript
this.dashboard = this.ngRedux.select(state => state.dashboard);
// or equivalent shorthand:
this.dashboard = this.ngRedux.select('dashboard');
```

This assigns a variable of type `Observable<Object>` to `this.dashboard`. So `dashboard.currentRobot.name` is not defined in this case; `name` is defined on the values that get pushed to the observable, not on the observable itself.

The `async` pipe is an Angular 2 construct that 'unpacks' a promise or observable when it resolves or gets a new value.

So in fact what you need to do is probably either this:

```typescript
this.currentName$ = this.ngRedux.select(state => state.dashboard.currentRobot.name);
```

or this:

```typescript
this.currentName$ = this.ngRedux.select('dashboard')
  .map(db => db.currentRobot.name);
```

or if you need null checks:

```typescript
this.currentName$ = this.ngRedux.select('dashboard')
  .map(db => db && db.currentRobot ? db.currentRobot.name : '');
```

and then in your template: `{{ currentName$ | async }}`.

*node the '$' on the end of currentName$: this is just a naming convention that says 'this property is an Observable'.

**Comment by justsayno** [comment]
Ahh I did suspect that. Now I see the pattern that I could use. Correctly if I'm wrong but say I have a component structure like this:

```javascript
AppComponent // container like in the counter example
     -DashboardComponent // a main 'view' in the application
           -RobotDetailComponent //A 'dumb' sub component of DashboardComponent
```

My state looks like this for example:

```javascript
export interface RootState {
  dashboard: DashbordState
}
export interface DashbordState {
  currentRobot: RobotModel
}

export interface RobotModel {
    name:string,
    assetCode: string,
    serial: string,
    image:string
}
```

And I wanted to pass all the values of the current robot to my RobotDetailComponent then I would do this in my ngInit on the DashboardComponent:

```javascript
  ngOnInit() {
    this.unsubscribe = this.ngRedux.subscribe(() => {
        this.applicationRef.tick();
    });
    this.currentRobot$ = this.ngRedux.select(state => state.dashboard.currentRobot);
  }
```

Then I could use those values in my template as I was wanting to:

```html
<h2>{{currentRobot.name}}</h2>
```

I ony wanted to clarify to make sure this is a good pattern and I was finding it hard to translate the way that I've used redux with React and this and its hard without a concrete more 'read world' example.

**Comment by justsayno** [comment]
Just to add to my example. I've been playing around with this and yes it works. But the thing I don't like about it is how it means that I'm passing around my whole 'Robot' object and the sub-components have to care about the implementation of that robot. What I'd like to achieve is having a `robot-detail` component like this:

```
import {Component, Input} from '@angular/core';

@Component({
  selector: 'robot-detail',
  template: require('./robot-detail.component.html')
})
export class RobotDetailComponent {
  @Input() name: string;
  @Input() assetCode: string;
  @Input() serial: string;
  @Input() image: string;
}
```

```
<div class="col-md-2 device-details">
    <h2>{{name}}</h2>
    <p class="label">Asset code</p>
    <p class='attribute-value'>{{assetCode}}</p>

    <p class="label">Serial</p>
    <p class='attribute-value'>{{serial}}</p>

    <div class='device-controls-wrapper smallitem'>
        <img class="img-responsive" src="{{image}}"/>
        <div class="device-controls clearfix">
            <span class="label label-inverse">
                Device<br>Controls
            </span>
            <a href="#" class="device-control pull-right">
                <img src="assets/icon/button_play.png"/>
            </a>
        </div>
    </div>
</div>
```

Then in my template for the dashboard component I want to be able to do something like

```
<robot-detail [name]="{{name}}" [assetCode]="{{assetCode}}"></robot-detail>
```

Whats the best pattern for this? Or am I thinking about it in a non-angular2 sort of way?

Forgive me I don't quite really understand what the observables advantages are over just binding the value to the template... But that comes from  a react background with Redux where I know that the way it is binding is very different. Just trying to figure out how Redux fits into this Observable model...

**Comment by justsayno** [comment]
Glourious! I looked further into this library and found the [angular2-redux-starter](https://github.com/rangle/angular2-redux-starter) that Rangle has done and looked into the dependencies and see you are using a beta version of the ng2-redux library.

Gave it a whirl and now I can get my app looking how I'd like using the approach in that starter! 

How far away is v3 and is there a lot that will likely change from whats described in the changelog (breaking changes I mean).

**Comment by SethDavenport** [comment]
Hi @justsayno sorry for the silence on this thread, busy week.

So to answer your question about the robot-detail component I'd be inclined to do something like this:

1. keep `RobotDetailComponent` exactly as you describe above
2. in the container component (i.e. where `RobotDetailComponent` gets used) do something like this:

```typescript
@Component({
  // etc.
  directives: [ RobotDetailComponent ]
  template: `
     <robot-detail
       [name]="{{currentRobot.name}}"
       [assetCode]="{{currentRobot.assetCode}}">
    </robot-detail>
     <!-- // whatever else -->  
  `
})
class DashboardComponent {
  currentRobot: RobotModel;
  subscription: Disposable;

  ngOnInit() {
    // ...
    this.subscription = this.ngRedux.select(state => state.dashboard.currentRobot)
      .subscribe(robot => this.currentRobot = robot);
  }}

  ngOnDestroy {
    this.subscription.dispose();
  }
}
```

**Comment by SethDavenport** [comment]
As for v3 beta, I'd like to at least get the DI changes and `@select` out soon. We're still going back and forth a bit about how `@dispatch` an `@dispatchAll` will work.

@e-schultz is this something we can do?

**Comment by justsayno** [comment]
@SethDavenport Thanks for that and no worries on the wait! I must have came to the same conclusion about the @Dispatch decorators since I didn't use them.

One thing I couldn't get my head around with the @Dispatch decorator is how that would works with DI. In the v2 I can inject my action creator service and use it. Can I do that in a decorator or do my action creators have to be just exported functions and not class methods?

Thanks again for your help! Would be interested to see what you guys think of [this other interesting ng2/redux project:](https://github.com/ngrx/store). Main thing I dont like about it is the lack of dev tools... But seems some discussion about getting it integrated. Thus far I preffer vanilla Redux!

**Comment by SethDavenport** [comment]
Yes - the `@dispatch` and `@dispatchAll` decorators are still experimental and we don't have a good DI story for them yet.

We're looking to push out 3.0 within the next week or so, without the dispatch decorators.  It will contain `@select` and the new DI-friendly bootstrapping approach, as well as some expanded documentation.

As for ngrx, that's also a perfectly good take on the redux pattern in Angular 2.  I haven't played too much with it myself but some of my colleagues are fans.

Where we are providing a redux wrapper that's idiomatic to Angular 2, they have taken the philosophy of redux but re-written it from scratch.  It's an interesting approach; I'm sure they've seen some good architectural benefits.  However what we gain is that we retain compatibility with the mature redux devtools and the community of interesting middlewares like redux-saga, etc.

Ultimately which one you choose will come down to your preference and your project's needs.

**Comment by SethDavenport** [comment]
@justsayno v3.0.x was released today, FYI.
