### ISSUE TITLE
Cannot import select from ng2-redux in example

### ISSUE THREAD

**Issue by igorilic** [angular-redux/ng2-redux#126]
After npm install from example folder, on npm start I have errors:

- ```[ts] Module '"... ng2-redux/lib/index"' has no exported member 'select' ```
- ``` [ts] Property 'configureStore' does not exist on type 'NgRedux<RootState>'``` 

I did not change the code from example.

**Comment by e-schultz** [comment]
@igorilic this should be fixed now if you pull the latest from master.
