### ISSUE TITLE
After updating to ng2-redux 3.0.5 - unit tests are failing

### ISSUE THREAD

**Issue by TobiasKrogh** [angular-redux/ng2-redux#127]
Hi,

it is me again with Unit test issues using ng2-redux. Updating to version 3 is very cool using the select decorator.

However, for my unit tests I tried to inject NgRedux as I do with every injectable via `beforeEachProviders` because else the tests complained about "No provider for NgRedux!". After adding `NgRedux` the tests complains about "Platforms have to be created via `createPlatform`!"

Any idea? This only happens in unit tests. The app itself runs fine. Unfortunately I found no particular information about the issue with `createPlatform` and also I found no example of tests when using NgRedux 3.x

My component:
```
import {
  Component,
  ViewChild
} from '@angular/core';

import { NgRedux } from 'ng2-redux';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'feed',
  styles: [ '' ],
  template: 'test'
})
export class Feed {
  constructor(private redux: NgRedux<any>) {}
}
```

My test:
```
import {
  it,
  describe,
  inject,
  beforeEach,
  beforeEachProviders
} from '@angular/core/testing';

import { TestComponentBuilder } from '@angular/compiler/testing';

import { NgRedux } from 'ng2-redux';

import { Feed } from './feed.component';

describe('Feed: Component', () => {
  let tcb, graphQL;

  // setup
  beforeEachProviders(() => [
    NgRedux,
    TestComponentBuilder
  ]);

  beforeEach(
    inject(
      [TestComponentBuilder], (_tcb) => {
        tcb = _tcb;
      }
    )
  );

  describe('initial state', () => {
    it('should have proper initial state', done => {
      tcb
        .createAsync(Feed).then(fixture => {
          const component = fixture.componentInstance;
          expect(true).toBe(true);
          done();
        })
        .catch(e => done.fail(e));
    });
  });
});
```

Cheers

**Comment by e-schultz** [comment]
@TobiasKrogh 

Thanks for bringing this up, when we changed how we bootstrap a ng2-redux app - we changed it so it requires an ApplicationRef. Working on a fix to make this optional so testing is easier. 

If you install `ng2-redux@3.0.8-beta.2`, what you should be able to do is in your beforeEachProviders, is create an instance of ng2-redux and configure it. 

I have an example of this on pull request for an angular2-redux starter which can can take a look at [here](https://github.com/rangle/angular2-redux-starter/pull/186/files) - soon I'll setup the example app to have proper unit testing.

But, the basics of it is:

```ts
// Configure NgRedux with mock store/etc.
  beforeEachProviders(() => [RioCounterPage, CounterActions, provide(NgRedux, {
    useFactory: () => {
      let ngRedux = new NgRedux(null);
      ngRedux.configureStore(combineReducers<any>({ counter }), {});
      return ngRedux;
    }
  })]);
```

Going to be doing a bit more testing on this, but let me know if this helps.

Thanks,

Evan

**Comment by TobiasKrogh** [comment]
@e-schultz wow that really helps... I can actually get my tests green again :) 

still trying to figure out the details but it seems I am able to make progress :) many thanks

**Comment by TobiasKrogh** [comment]
took some time and investigation but finally all tests are green again

**Comment by SethDavenport** [comment]
Keeping issue open until 3.0.8 is out of beta.

**Comment by TobiasKrogh** [comment]
Since 3.1.0 is out I would say this ticket can be closed :)

**Comment by e-schultz** [comment]
@TobiasKrogh closing the issue, if you have any other questions / feedback - happy to address them. Thanks for the feedback so far,

Evan
