### ISSUE TITLE
Selecting ImmutaleJS states, state function not executing...

### ISSUE THREAD

**Issue by brainlid** [angular-redux/ng2-redux#129]
I'm using ng2-redux version 2.3.3 with Ionic2, Angular 2 RC2 and ImmutableJS.

I'm trying to display a list of items and open a single item to a new ionic page. As an example, lets say I have list of blog posts in an Ionic2 page component. When the user selects a post, it transitions to a page displaying the "show" page. From here they can Edit the post in a popup Modal. When the post is saved, the Modal is closed and the "show" page is displayed again. I want the post to be loaded by an observable so any change to the post will show up automatically.

Here's the sample data-structure (Immutable js). 

The state would look like this...

```typescript
Map<string, any>({
  posts: Map<string, Post>({})
})
```

The idea is that it tracks the posts like a hash with the ID as the key and the object as the value. Making accessing a specific item in the list faster, since I expect several hundred items to thousands in the list. Expressing this in simple javascript might look like this.

```javascript
let state = {
  posts: {"1": {id: "1", title: "Hello World"}}
}
```

Where a Post is defined as:

```typescript
export const PostRecord = Record({
  id: null,
  title: "",
  author: "",
  published: false,
  body: null
});
export class Post extends PostRecord {
  id: string;
  title: string;
  author: string;
  published: boolean;
  body: string;

  constructor(props) {
    super(props);
  }
}
```

So I thought I could pass the ID of the post to display to the show page and try and subscribe to that change.

```typescript
@Component({
  templateUrl: 'build/pages/settings/posts/post-page.html',
  pipes: [AsyncPipe],
})
export class PostPage {
  post$: Observable<any>;
  post: Post;

  constructor(private params: NavParams, private ngRedux: NgRedux<StoreType>) {}

  ngOnInit() {
    // this correctly gets the desired post, but it isn't being "observed"
    this.post = this.ngRedux.getState().getIn(["posts", this.params.get("post_id")])

    // this doesn't execute the state function...
    this.post$ = this.ngRedux.select(state => {
      debugger
      return state.get("posts").get(this.params.get("post_id")
    )});
  }
```

I've tried every way of expressing this I can think of. However, the "select" function isn't even being executed. I'm sure I'm misunderstanding something. 

Do you have any tips or pointers? Am I going about this the wrong way?

**EDIT:** Fixed "zone$" to "post$" for my sample code. Later comment references it as "zone$"

**Comment by dagstuan** [comment]
Are you ever subscribing to the returned observable (`zone$`)? I dont think your select-function will be called unless you have any subscribers.

**Comment by brainlid** [comment]
Thank you for the response. After digging around both on previous issues [here](https://github.com/angular-redux/ng2-redux/issues/116) and on SO, got it working with this change...

```typescript
export class PostPage {
  post: Post;
  postSubscription: any;

  constructor(private params: NavParams, private ngRedux: NgRedux<StoreType>) {}

  ngOnInit() {
    this.postSubscription = this.ngRedux.select(state => {
      return state.get("posts").get(this.params.get("post_id"))
    }).subscribe(post => this.post = post);
  }

  ngOnDestroy() {
    this.postSubscription.unsubscribe();
  }
}
```

I'm still very new to Rx and ng2-redux. So My problem was really not understanding Observables. Thanks for the tip that put me on the right path.

Looking forward to being able to use ng2-redux v3 syntax with decorators. :) It is currently pinned to angular 2 rc1, I'm on rc2.
