### ISSUE TITLE
Angular 2 Quickstart

### ISSUE THREAD

**Issue by talktough** [angular-redux/ng2-redux#154]
I went through the instructions on the Angular 2 website in the 5 minute quickstart -

https://angular.io/docs/ts/latest/quickstart.html

It all works fine and I can see the page showing My First Angular 2 App.

I then npm install --save ng2-redux and it looks like everything works ok and ng2-redux appears in node_modules.

When I try to bootstrap ng2-redux by

import { NgRedux } from 'ng2-redux';
bootstrap(App, [ NgRedux ]);

I get Error loading http://localhost:3000/ng2-redux as "ng2-redux" from http://localhost:3000/app/main.js in the browser.

I've gone over my installation a few times and I can't see anything I've done wrong but could someone give me a suggestion as how to fix this please because I really want to use redux with Angular 2.

Thanks

**Comment by SethDavenport** [comment]
If I recall correctly the angular2 quickstart is based on SystemJS which means you need to do a little extra config over and above a simple `npm install --save ng2-redux`.

Npm will install the files in `node_modules`, but SystemJS isn't smart enough to look there automatically when it resolves imports. My recommendation is to find this portion of the quickstart's `system.config.js`:

```javascript
  var map = {
    'app': 'app', // 'dist',
    '@angular': 'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs': 'node_modules/rxjs'
  };
```

and change it to

```javascript
  var map = {
    'app': 'app', // 'dist',
    '@angular': 'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs': 'node_modules/rxjs',
    'ng2-redux': 'node_modules/ng2-redux'
  };
```

Let me know if that doesn't work and I'll dig a little deeper (I mostly use webpack these days so my systemJS skills are a little weak :)

**Comment by talktough** [comment]
Hi Seth

Thanks very much for your suggestion - unfortunately it doesn't work although it does sound like that is the problem.

I've been using browserify and webpack for a while now and normally I would use webpack for preference because of the work I have been doing with react/redux.

I might be working on an Angular 2 project next so I thought I would start learning about it and I just picked up the stuff of the Angular 2 website because I thought that would be the simplest way to go. I also really like working with redux so ng2-redux sounds like a really good option.

When I found your solution didn't work I had a look on SystemJS and this does seem like something that lots of people have run into although I didn't really see a simple solution. So I guess it seems kind of odd to me for a great number of the Angular 2 examples and seeds to use SystemJS because it would seem to make things more difficult than they need to be - but I've only just started looking at it so what do i know :0)

Its unfair to ask, particularly as it doesn't seem to be an ng2-redux problem,  but if you got any further suggestions I would very grateful.

Thanks very much

Chris

**Comment by talktough** [comment]
I managed to get this going by setting the following in map in system.config.js (after the bits in the quick start)

'ng2-redux': 'node_modules/ng2-redux/lib',
'redux':  'node_modules/redux/dist/redux.min.js',
'lodash': 'node_modules/ng2-redux/node_modules/lodash/'

and in packages (after the bits in the quick start)

'ng2-redux': { main: 'index.js', defaultExtension: 'js' }

That bit about lodash looks a little suspect to me because it might be used in other packages and in all honesty the webpack approach looks a lot easier so I think I will go for that.

Thanks Seth for your help.

**Comment by SethDavenport** [comment]
Great, glad it worked out.
