### ISSUE TITLE
Data fetch advice

### ISSUE THREAD

**Issue by talktough** [angular-redux/ng2-redux#161]
I have a users array in the store that I would like to populate before entry to a component.

As a first go I created a data fetch action to fetch the data via an http service and then on return to dispatch an action with the data as the payload then the reducer populates the users array.

That all works fine and the store gets the right values but at the moment I am calling the data fetch action in ngOnInit in the component. I don't really like that because it couples the data fetch to the component.

When I was using react I called the data fetch action in the react router EnterHook to cater for this situation. 

It seems like the angular 2 router has CanActivate that I might be able to use in the same way but I've had problems getting it to call the action because you have to return an Observable<boolean> that the CanActivate can watch for completion of the Observable.

I'm thinking that I might be over complicating things here - does anybody have a better way of doing the data fetch before entering the component ?

Thanks

**Comment by SethDavenport** [comment]
Hmm - my inclination would also have been to do the fetch in the `ngOnInit`. Although I would have done this in the smart component at the top level of the route, so as not to reduce the re-usability of any presentational components.

If you want to use `CanActivate`, you can still return an observable if you do something like:

```typescript
import { CanActivate } from '@angular/router';
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { NgRedux } from 'ng2-redux';

@Injectable()
export class DataFetchGuard implements CanActivate {
  constructor(
    private http: Http,
    private ngRedux: NgRedux) {}

    canActivate() {
      return http.get('/some/stuff')
        .map(response => {
          ngRedux.dispatch({ type: STUFF_FETCH_OK, payload: response.json() });
          return true; // Allow the route activation.
        })
        .catch(error => {
          ngRedux.dispatch({ type: STUFF_FETCH_FAILED, error });
          return false; // Disallow the route activation (if that's what you want)
        });
    }
}

**Comment by SethDavenport** [comment]
That said, using a route guard may not be the best option - you may not want to hold up the route change while waiting for the HTTP call to return - it may result in the appearance of the app freezing without visual feedback to the user.

**Comment by SethDavenport** [comment]
Another option might be to simply dispatch the 'fetch' action and return `true` immediately (a synchronous route guard); and then use something like a [redux-observable](https://github.com/redux-observable/redux-observable) Epic to handle the actual HTTP call.

In general I'm starting to think that Epics are the way to go for this type of asynchronous action anyway.

In other words, make a route guard like this:

```typescript
import { CanActivate } from '@angular/router';
import { Injectable } from '@angular/core';
import { NgRedux } from 'ng2-redux';

@Injectable()
export class DataFetchGuard implements CanActivate {
  constructor(
    private http: Http,
    private ngRedux: NgRedux) {}

    canActivate() {
       ngRedux.dispatch({ type: FETCH_STUFF });
       return true; // No need to return an observable - this is a synchronous guard.
    }
}
```

And then an epic like this:

```typescript
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/filter';
import 'rxjs/add/operator/catch';

@Injectable()
export class DataFetchEpics {
  constructor(private http: Http) {}

  getStuff = (action$: Observable<IPayloadAction>) => {
    return action$.filter(({ type }) => type === FETCH_STUFF)
      .flatMap(() => this.http.get('/some/stuff')
          .map(result => ({
            type: FETCH_STUFF_OK,
            payload: result.json()
          }))
          .catch(error => Observable.of({ type: FETCH_STUFF_FAILED });
  }
}
```

... and finally wire the epic into your store with the epically-named `createEpicMiddleware`:

```Typescript
@Component({
  /* ... */
})
export class App {
  constructor(
    private ngRedux: NgRedux<IAppState>,
    private epics: DataFetchEpics) {

    middleware.push(createEpicMiddleware(this.epics.getStuff));
    ngRedux.configureStore(rootReducer, {}, middleware);
  }
};
```

**Comment by SethDavenport** [comment]
At this point the fetch is totally decoupled from the component or from the route guard - FETCH_STUFF is essentially fire-and forget; the Epic takes care of resolving the data and passing it to the reducers (via FETCH_STUFF_OK) in the background.

At this point I'm only left wondering if the route guard is even necessary - it might be better to simply listen for a route changes by subscribing to `Router.events`.

**Comment by talktough** [comment]
Wow that's a really comprehensive answer Seth thanks very much.

I will take a look at redux-observable and close the issue once I have worked it through.

Chris

**Comment by SethDavenport** [comment]
No problem. Feel free to reach out with any questions.

**Comment by SethDavenport** [comment]
Closing for now. Feel free to re-open if you run into other issues.
