### ISSUE TITLE
Cannot run the example

### ISSUE THREAD

**Issue by zalmoxisus** [angular-redux/ng2-redux#165]
Trying to figure out [an issue](https://github.com/zalmoxisus/redux-devtools-extension/issues/167), wanted to run the counter example. First it requires `immutable` library. Then after installing it, there's an error in `./containers/App.ts` (38,33): 
`Supplied parameters do not match any signature of call target.`

I'm not too familiar with typescript, and apologize if I'm missing something here.

**Comment by SethDavenport** [comment]
Hi @zalmoxisus, thanks for the bug report.

There are a couple of things going on here:

* The warning about immutable - this is in fact benign.  ng2-redux optionally depends on immutableJS in the sense that it will `require()` it if it exists, but will work perfectly fine without it. The reason for this is that we want to be able to allow people to use `@select` and have it work regardless if whether their store contains Immutable types or plain JS objects.

However when we're included via webpack, it's not understanding the conditional require on our end and outputs a warning.  We'll look to suppress this going forwards.

* The typescript error is a legit bug on my part: we need to tell Typescript that the `options` parameter is optional.  I have fixed this in #164.  The workaround is to pass an empty object in this case: `[ ...enhancers, devTool.enhancer({}) ]`.

**Comment by SethDavenport** [comment]
PS huge fan of the chrome extension - it's saved me a lot of headaches!

**Comment by SethDavenport** [comment]
Keeping the issue open pending resolution of the webpack warning. However you should be able to run the example app with `npm run dev` now.

**Comment by SethDavenport** [comment]
@clbond @e-schultz Turns out webpack's not a huge fan of the conditional require in `utils/get-in.ts`. It doesn't break anything, but we do get a scary-looking warning in the console and a large stack trace in the browser console.

We should see if there's a way to work around this.

**Comment by zalmoxisus** [comment]
@SethDavenport, thanks for the details and the feedback! It's a good example not only for using redux with angular, but also for integrating it with typescript.

Regarding conditional dependencies, I think easier is to just use it explicitly, so if I want to use the library with immutableJS, I would require `ng2-redux/immutable` instead of `ng2-redux`. Less magic, but it will also avoid including unnecessary libraries in the final bundle, just because I forgot to remove it form `node_modules`.

**Comment by clbond** [comment]
Hmm. I will take a look at this today. Thank you

**Comment by SethDavenport** [comment]
Thanks Chris.

I wonder if there's a way to do things that doesn't know about Immutable explicitly. E.g. look for a function called getIn on the selected object and call it if it exists.

Or for regular props try something `foo.bar || foo.get('bar')`
