### ISSUE TITLE
@select gives Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by razor-x** [angular-redux/ng2-redux#166]
Trying to get a minimal working example setup, but I can't get past this error:

Line with `if (delete this[key]) {`) (https://github.com/angular-redux/ng2-redux/blob/master/src/decorators/select.ts#L32)

`Uncaught TypeError: Cannot convert undefined or null to object`

Can't debug with the example counter due to #165.

I can see that my store is created correctly (via `getState()`) and I know the component otherwise works correctly if I set the `todos` property manually.

From https://github.com/rxlabs/tasty-todos-ng2/blob/bug-select/app/containers/visible-todo-list/visible-todo-list.component.ts
```js
import { select } from 'ng2-redux';
import { Component } from '@angular/core'

import { TodoList } from '../../components/todo-list/todo-list.component'

@Component({
  directives: [TodoList],
  selector: 'visible-todo-list',
  template: `
    <todo-list [todos]="todos"></todo-list>
    `
})

export class VisibleTodoList {
  // todos = [{name: 'thing'}] // works if I uncommnet this
  @select() todos              // and remove this
}
```

From https://github.com/rxlabs/tasty-todos-ng2/blob/bug-select/app/containers/app/app.component.ts
```js
import { NgRedux } from 'ng2-redux';
import { Component } from '@angular/core'

import { store } from '../../store'
import { VisibleTodoList } from '../visible-todo-list'

@Component({
  directives: [VisibleTodoList],
  selector: 'tasty-app',
  template: `
    <h1>{{title}}</h1>
    <visible-todo-list></visible-todo-list>
    `
})

export class App {
  constructor(private ngRedux: NgRedux) {
    this.ngRedux.provideStore(store)
  }
  title = 'Tasty Todos in Angular 2'
}
```

**Comment by SethDavenport** [comment]
Hi @razor-x 

I was able to get your example to work using the following:

```typescript
import { NgRedux, select } from 'ng2-redux';
import { Component } from '@angular/core'

import { TodoList } from '../../components/todo-list/todo-list.component'

@Component({
  directives: [TodoList],
  selector: 'visible-todo-list',
  template: `
    <!-- since select gives you an observable, you need to unbox it with | async before
       -- adding it to ngFor in the child component.
       -->
    <todo-list [todos]="todos | async"></todo-list>
    `
})
export class VisibleTodoList {
  //@select() todos;
  private todos;

  constructor(private ngRedux: NgRedux<any>) {
    this.todos = ngRedux.select('todos');
  }
}
```

I made two changes:

1. `select` returns an observable, not a list. That means that you either need to subscribe to it or use angular's `async` pipe in the template as I did above.
2. I used the `.select` function for now since the decorator isn't working in your case.

There must be something I'm missing about the setup for, 2; we're still looking into it.

**Comment by SethDavenport** [comment]
As for #165, it's been fixed.

**Comment by SethDavenport** [comment]
@kosz @e-schultz : I'm curious about the line that's generating the error: https://github.com/angular-redux/ng2-redux/blob/master/src/decorators/select.ts#L32

Should it be `if (delete target[key])` instead? What is `this` in this scenario?

**Comment by SethDavenport** [comment]
I checked out razor-x's repo and branch (thanks for that) and hacked the local `node_modules` with this: https://github.com/angular-redux/ng2-redux/pull/168

It appears to fix the issue with `@select` in his repo.

**Comment by razor-x** [comment]
@SethDavenport Thanks for the quick reply.

I can confirm the changes you made work: either bypassing `@select()` or using `@select()` after hot-applying the patch.

One possible suggestion for the docs: as someone just getting up to speed with Observables and Angular 2, it wasn't obvious to me why the `async` pipe was needed, or the meaning of the (ignored) trailing`$`. A brief note and/or link for others seeing that here first might help avoid some mystery.

**Comment by SethDavenport** [comment]
Sure, good suggestion.

**Comment by e-schultz** [comment]
@razor-x 3.3.1 has been published today, thanks for raising the issue.
