### ISSUE TITLE
set store in the bootstrap

### ISSUE THREAD

**Issue by hlehmann** [angular-redux/ng2-redux#171]
Is it possible to initiate the store in the bootstrap with something like this:
```typescript
    let store = createStore(
        combineReducers(reducers),
    );

    let providers = [
        NgRedux,
        provideStore(store),
    ];

    bootstrap(App);
```

**Comment by SethDavenport** [comment]
We used to work that way prior to version 3. However we abandoned it because it's too inflexible. It forces you to configure all your middlewares and enhancers before Angular's dependency injector is started up; what happens if you want to use an Angular service from within middleware?
