### ISSUE TITLE
DevTools component throws "ReferenceError: window is not defined" when run on node using Universal

### ISSUE THREAD

**Issue by jonoward** [angular-redux/ng2-redux#172]
When I use ng2-redux using Angular2 Universal to execute server side on node, I get an error when the devtools component is loaded - "ReferenceError: window is not defined"

This is the offending line:
https://github.com/angular-redux/ng2-redux/blob/master/src/components/dev-tools.ts#L2

Would it be possible to convert the falsy check to a typeof window == "undefined" check?

(I've tried this by hacking the generated JS and had no further issues)

I can submit a PR if you'd like?

Thanks

**Comment by SethDavenport** [comment]
Dev tools don't make a lot of sense on the server side - would it make more sense to not register the devtools store enhancer when on the server (via some config property for example)?

That said, the change you suggest seems simple enough - if you feel like making a PR that would be awesome :)

**Comment by jonoward** [comment]
Oh yeah I'm not trying to use devtools on the server, I don't have the devtool enhancer included when I configure the store, but I think that line causes an issue just by virtue of the component being imported in index.ts. I'll try get a PR over to you asap. Thanks for getting back to me

**Comment by SethDavenport** [comment]
OK yeah that makes sense 👍

**Comment by jonoward** [comment]
Thanks guys, unfortunately this commit didn't fix the issue for me, as it's a run-time error in node. I've issued a PR if you want to have a look. Sorry I took so long to get this over. Cheers
