### ISSUE TITLE
Pre select hook

### ISSUE THREAD

**Issue by TobiasKrogh** [angular-redux/ng2-redux#173]
Hey,

I was wondering whether it is possible to hook into getState before the `@select` decorator accesses the storage. I am using ImmutableJS but also another package that requires me to call an ensuring function (`ensureState`) before accessing the store. This of course makes it impossible for me to use the syntactic sugar in combination with ImmutableJS.

Example:
```
@select(s => ensureState(s).getIn(['counts', 'firstCount'])) firstCount$: Observable<number>;
```

Can I somehow hook into the state getter before the decorator fetches the store so I can by default have the state wrapped by the `ensureState` method (coming from https://github.com/mattkrick/redux-optimistic-ui).

Any help would be appreciated.

EDIT: `ensureState` is needed everywhere I access the store.

Cheers

**Comment by e-schultz** [comment]
Is this currently throwing an error? taking a quick look at the redux-optimisitc-ui, and the example snippet that you have, I don't see why this wouldn't work, as `s` is basically the value of `getState()`.

**Comment by TobiasKrogh** [comment]
There is no error in the upper construct. The idea was to make use of the syntactic sugar explained in https://github.com/angular-redux/ng2-redux/blob/master/docs/immutable-js.md. So basically transforming this:

```
@select(s => ensureState(s).getIn(['counts', 'firstCount'])) firstCount$: Observable<number>;
```

into this:

```
@select(['counts', 'firstCount']) firstCount$: Observable<number>;
```

Which currently is not possible because I have to call ensureState on my state in order for redux-optimistic-ui to return the proper state. Therefore I always have to use the longer syntax. My question was whether there is a possibility to have a general mechanism doing `s => ensureState(s)` so I can use the nice and clean syntax for the `@select` decorator.

**Comment by e-schultz** [comment]
@TobiasKrogh Thanks for clarifying - been thinking about this for a day or two, but haven't been able to come up with clean way of handling this, at least at a library level.

If I get a chance, I'll see if I can play around with an example decorator that hooks calls select after doing an ensureState. 

One thing that I do suggest though, is placing your selectors along with your reducers, ie.

```js
// some-feature.reducer.ts
export counts(state,action) {
    return state;
}
export firstCount = (state) => ensureState(s).getIn(['counts', 'firstCount'])
```

Then in your components that need to make use of it,

```js
import { firstCount } from './your/reducers';

@Component({})
export class MyComponent {
    @select(firstCount) firstCount$:Observable<number>
}
```

This helps make it so your components need to know less about the structure of your state, allows your selectors to be reusable, and if you need to refactor your state/reducers - it limits the number of areas you need to refactor to address the change.

**Comment by TobiasKrogh** [comment]
@e-schultz Thanks for your feedback. It would be great if we find a solution.

I did not yet thought about putting the selectors alongside the reducers, nice idea. Thanks. Seems definitely worth it.

**Comment by TobiasKrogh** [comment]
@e-schultz Sorry for not responding for such a long time. I was not able to do the suggested optimization but I definitely will. For me this issue can be closed... still a general way to hook into the store somehow would be great

**Comment by danielfigueiredo** [comment]
I gave this a thought too and agreeing with @e-schultz it is hard to think about something clean.
Having said that, @TobiasKrogh if what you want is that all `@select` calls first call ensureState sending down the state itself. You could decorate the decorator :P

```typescript
export function selectEnsureState<T>(
  selector?: PropertySelector | PathSelector | FunctionSelector<any, T>,
  comparator?: Comparator): PropertyDecorator {
  return select(s => selector(ensureState(s)), comparator);
}
```
Basically you would instead use your own decorator that wraps ng2-redux's select decorator
I haven't tested this code, but it looks reasonable to me. Finally you could do:
```typescript
class MyContainer {
  @selectEnsureState(s => s.getIn(['counts', 'firstCount'])) firstCount;
}
```

**Comment by danielfigueiredo** [comment]
Actually I just realized that this is not what you want, since it is not going to be "before the @select decorator accesses the storage"

**Comment by TobiasKrogh** [comment]
@e-schultz Hi, sorry (once again) for not responding for such a long time... been very busy lately. I took your advice and placed selectors along my reducers respectively migrated them stepwise. This is really clean and I feel it is fine to do the `ensureState` call there. Thanks for your time! Will close
