### ISSUE TITLE
Consider adding ability to register epics dynamically?

### ISSUE THREAD

**Issue by ddestevez** [angular-redux/ng2-redux#174]

**Comment by SethDavenport** [comment]
Hi @ddestevez can you clarify what you mean? 

Do you mean the ability to add them after having already configured the store?

**Comment by ddestevez** [comment]
Yes, so I don't have to load all providers at app start

**Comment by SethDavenport** [comment]
Looks like redux-observable supports that: https://github.com/redux-observable/redux-observable/blob/master/docs/recipes/AddingNewEpicsAsynchronously.md

**Comment by ddestevez** [comment]
Thanks @SethDavenport for the info. Awesome work by the way!!!
