### ISSUE TITLE
update to Typescript 2

### ISSUE THREAD

**Issue by SethDavenport** [angular-redux/ng2-redux#181]
This will likely involve:

* updating the compiler
* getting rid of typings in favour of the new `@types` thing.
* removing `typings` from peer deps

**Comment by eddedd88** [comment]
when can I expect this task to be done?

I am using [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) in my project and they use typescript2

**Comment by SethDavenport** [comment]
You should still be able to use it as-is - we publish the transpiled source to npm.

**Comment by eddedd88** [comment]
you are right, I am already using it.
