### ISSUE TITLE
Update version of peerDependencies

### ISSUE THREAD

**Issue by zhang-z** [angular-redux/ng2-redux#187]
Hi, is it OK to update "zone.js" from "0.6.12" to "^0.6.12" in package.json?

**Comment by SethDavenport** [comment]
I'm pretty sure Angular2 RC5 has a fixed dependency on 0.6.12. So you may find that it doesn't work.

**Comment by SethDavenport** [comment]
I stand corrected: https://github.com/angular/angular/blob/master/modules/%40angular/core/package.json#L12

Let me look into it.
