### ISSUE TITLE
Use of invariant?

### ISSUE THREAD

**Issue by SethDavenport** [angular-redux/ng2-redux#191]
We use assertions in a few places to enforce that parameters are the correct type - for example in `NgRedux.select`. Is this strictly necessary given that types are enforced at build time with typescript?

Or is this for those few brave souls who are using Angular2 with ES5?

**Comment by e-schultz** [comment]
Largely carry-over from ng-redux and when this was ES5/6 and not TypeScript - could potentially remove these checks. Sort of relates to the conversation we were having the other day of 'how defensive should we be with type checks', especially when using TypeScript now.

**Comment by SethDavenport** [comment]
OK - yeah that's what I figured. We could drop some code if we decided to go with build-time checks only.

**Comment by SethDavenport** [comment]
There are a few cases where we use it for non-type-check related things - e.g. preventing double store initialization for example. Let's leave it in for now.
