### ISSUE TITLE
 ReferenceError: process is not defined

### ISSUE THREAD

**Issue by zhenyanghua** [angular-redux/ng2-redux#202]
When used with lite-server, the dependency redux throw a node server issue for the required dependency redux. Is that something to do with ng2-redux?

(index):43 Error: ReferenceError: process is not defined
	    at Object.eval (http://localhost:3000/node_modules/redux/lib/index.js:38:5)
	    at eval (http://localhost:3000/node_modules/redux/lib/index.js:47:4)
	    at eval (http://localhost:3000/node_modules/redux/lib/index.js:48:3)
	    at Object.eval (http://localhost:3000/node_modules/ng2-redux/lib/components/ng-redux.js:14:15)
	Evaluating http://localhost:3000/node_modules/redux/lib/index.js
	Evaluating http://localhost:3000/node_modules/ng2-redux/lib/components/ng-redux.js
	Evaluating http://localhost:3000/node_modules/ng2-redux/lib/index.js
	Evaluating http://localhost:3000/actions/session.actions.js
	Evaluating http://localhost:3000/app/app.component.js
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js

**Comment by SethDavenport** [comment]
Do you have a repo you can share to help reproduce this?

**Comment by SethDavenport** [comment]
Are you by any chance working with the angular2 quickstart config? I went ahead and set up a simple ng2-redux  counter based on their SystemJS/LiveServer toolchain and got it working:

https://github.com/SethDavenport/ng2-redux-systemjs-example/blob/master/README.md

It's working fine for me.

**Comment by SethDavenport** [comment]
I suspect your problem can be seen from this line in the stack trace:

```
Evaluating http://localhost:3000/node_modules/redux/lib/index.js
```

Looks like SystemJS is importing redux from `node_modules/redux/lib/index.js`; it should be importing the bundled version in `node_modules/redux/dist/index.js` instead.

Try putting this in your `systemjs.config.js`:

```javascript
  var map = {
    /* ... */
    'ng2-redux':                  'node_modules/ng2-redux',
    'redux':                      'node_modules/redux',
  };

  var packages = {
    /* ... */
    'ng2-redux':                  { main: 'lib/index.js', defaultExtension: 'js' },
    'redux':                      { main: 'dist/redux.js', defaultExtension: 'js' },
  };
```

**Comment by zhenyanghua** [comment]
@SethDavenport Thank you!!!! You just solved the missing peace!!!!

**Comment by SethDavenport** [comment]
Awesome, happy to help.
