### ISSUE TITLE
Missing metadata.json files for AoT compilation

### ISSUE THREAD

**Issue by dagstuan** [angular-redux/ng2-redux#223]
Currently the library does not support AoT compilation due to missing metadata.json files that need to be included along with d.ts-files.

See:

https://github.com/orizens/angular2-infinite-scroll/issues/77#issuecomment-245027350
https://github.com/angular/angular/issues/11262#issuecomment-244472000
https://github.com/angular/angular/issues/11262#issuecomment-244489405

**Comment by e-schultz** [comment]
Looking into getting AoT support in soon, and how this works with the `@select` decorator - have been running into some issues with that, and would like to get that resolved soon as AoT will be important for many projects.

Thanks for letting us know about the metadata.json / links to other issues - will try and get this resolved soon.

**Comment by duydao** [comment]
Thanks for looking into this! In the meantime, is there any workaround for this issue?

**Comment by h2qutc** [comment]
Hi, Did anyone fix this issue ?

**Comment by e-schultz** [comment]
Been busy traveling for work lately and haven't had as much time to work on this, but have a test module published at `4.0.0-aotbeta.3` - still not fully working.

One error once I've gotten past the NgModule error, is how it behaves when you pass functions into selectors.

```
export const stuffSelect = n=>n.tuff;
export class Stuff {
  @select(n=>n.stuff) thisWillCauseAnError$
  @select(stuffSelect) thisWilNotCauseAnError$
}
```

If anyone has a demo repo with an AoT app working that they could point me at to help play around with as a test bed, that would be great.

**Comment by e-schultz** [comment]
Some update/progress:

Working on a repo with master of angular-cli.

https://github.com/e-schultz/ng2-redux-aot-example/pull/1

Have it so things don't throw errors, however the `@select` decorator just fails to work, will investigate further.

**Comment by hasangilak** [comment]
i had this problem with ngc over NgRedux<RootState> error which could be handle like this
you can safely add ReduxWrapper as a provider to NgModule now 
   ```
 import {Injectable} from "@angular/core";
 import {NgRedux} from "ng2-redux/lib/index";
 import {IAppState} from "./../store/store";
        
 @Injectable()
 export class ReduxWrapper {
      private redux: NgRedux<IAppState>;
    
      constructor() {
        this.redux = new NgRedux<IAppState>();
      }
 }
```

**Comment by hasangilak** [comment]
also there must be another work around for combineReducers function . this style ditch the error of re-exporting Reducer over ngc compilation 
`<Reducer<IAppState>>combineReducers<IAppState>`

**Comment by hasangilak** [comment]
also there is a problem with redux library which throws an error on NODE_ENV === "productions". no way to handle this ...

**Comment by SethDavenport** [comment]
@hasangilak regarding the NODE_ENV === "production" error - are you using angular-cli or webpack by any chance?

**Comment by SethDavenport** [comment]
If you're using angular-cli I believe they've fixed this in beta-18. If you're using webpack, you'll need to use `webpack.DefinePlugin` to provide a value for `process.env` in the browser environment: 

```javascript
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
})
```

**Comment by SethDavenport** [comment]
@dagstuan have you tried the latest ng2-redux 4.0.0 beta 6? I believe it resolves a number of AoT issues.

**Comment by SethDavenport** [comment]
Closing for now.  If you're still having AoT issues, be sure to reference #234 for the latest discussion.

**Comment by dagstuan** [comment]
Hey, sorry about the late reply. I havent had issues with it lately as I've been waiting a while to try and implement it again :) But it looks like you guys have it under control. Thank you! :)
