### ISSUE TITLE
Multiple subscribers when using multiple async pipe on the same selector?

### ISSUE THREAD

**Issue by NetanelBasal** [angular-redux/ng2-redux#229]
For example, I am using this code in my component:
```js
 @select(['session', 'isLoggedIn']) isLoggedIn$ : Observable<boolean>;
```

If In my template I am using `isLoggedIn$` more than one time, for example:

```html
<a *ngIf="!(isLoggedIn$ | async)">Sign in</a>
<a *ngIf="(isLoggedIn$ | async)">Some route</a>
<a *ngIf="(isLoggedIn$ | async)">Some route</a>
```

The code above will create three subscriptions? or they sharing the same subscription?

**Comment by spock123** [comment]
I'm pretty sure it's only one subscription.
This is an @angular/core  async optimization.

**Comment by SethDavenport** [comment]
That's also my understanding.

**Comment by johnhamm** [comment]
Async pipe does not use share or have any optimizations for multiple repeat uses in a template.  It creates a subscription for each use of the Async pipe in a template.  :(

**Comment by tuongaz** [comment]
yes, it does not use share. You can confirm it by adding `.do(() => console.log('Called'))` in your Observable. You'll see in the Console multiple 'Called'.

**Comment by choopage** [comment]
Any idea what is the solution to using multiple async pipe on the same variable$?

**Comment by harunurhan** [comment]
@choopage using the `share` operator manually on the observable.

Check this out:
http://stackoverflow.com/questions/40742181/performance-of-using-same-observable-in-multiple-places-in-template-with-async-p

**Comment by nikhilnayyar002** [comment]
i am currently facing problem like:

this.discussions$=this.db.collection("discussions").valueChanges();
------------------------------------------------

 li class="clearfix shadow-scale" *ngFor="let discussion of discussions$ | async" 

..............
................
................

 li class="clearfix shadow-scale" *ngFor="let discussion of discussions$ | async" 
...............
...............
................

See valuechanges gives the value and complete. So if the earliest async pipe subscribes the second async pipe will probably null. if i put a new document in 'discussions' collection then both of them will update and then  the second async pipe will not be null. 

Moreover:

 this.discussions$=this.db.collection("discussions").valueChanges()
                   .pipe(tap(ev => console.log(ev))); 
-----------------------
here it logs only once.
Any one using firestore might know the answer.

**Comment by MithrilMan** [comment]
what do you think about the solution outlined in this article?
https://medium.com/@ofirrifo/extract-multiple-observables-with-the-async-pipe-in-angular-b119d22f8e05
It seems nice to me, basically using
`*ngIf=”{key: obsarvable | async} as data”`
the result is always true, so the block is always rendered, and you have just to check against data to see if it's null.
Placing this kind of code in the parent block allow then to have a single subscription

**Comment by nikhilnayyar002** [comment]
Yeah its a good workable solution when we are working in template. Also don't need to use share operator. It solves mine too.
