### ISSUE TITLE
devtools v3 support

### ISSUE THREAD

**Issue by lanocturne** [angular-redux/ng2-redux#23]
Hi @wbuchwalter. Just wander does current ng2-redux support redux-devtools v3.0.1? If so could you update the example?

**Comment by wbuchwalter** [comment]
Yes it should work just fine.
I will try to update the example when I have some free time.
Thanks.

**Comment by SethDavenport** [comment]
We're currently recommending to use the chrome extension version of the devtools: https://github.com/zalmoxisus/redux-devtools-extension, for several reasons:

1. Less impact on your code - turning them on is a one-line change
2. The extension is kept up to date for you
3. You no longer end up with your app having a dev-dependency on React.

You can see an example of how to turn this feature on in the README.md for the lastest version of ng2-redux.
