### ISSUE TITLE
recommend watching: typed redux store...

### ISSUE THREAD

**Issue by born2net** [angular-redux/ng2-redux#231]
I myself am a big fan of redux, and while I am currently investigating moving my projects to this lib, I wanted to share this video with you guys: 
https://www.youtube.com/watch?v=bEkPEnudm7s   (highly recommend you watch)

if I move to this lib I will still use ImmutableJS, and I am wondering if people who use this lib also use ImmutableJS in their reducers and data models?

Regards,

Sean

**Comment by simpulton** [comment]
This is a self-promoting advertisement in the form of an issue.

**Comment by born2net** [comment]
just wanted to share... fixed, closed!
