### ISSUE TITLE
Problem with NgReduxModule in an Ionic 2 rc0 project

### ISSUE THREAD

**Issue by danielcrk-cn** [angular-redux/ng2-redux#232]
Hi,

This might not be an issue with ng2-redux as much as me doing something wrong, but here goes:

In app.module.ts, as soon as i `import { NgReduxModule, NgRedux } from 'ng2-redux';` and add `NgReduxModule` to imports, the app fails on startup with the error `Uncaught ReferenceError: module is not defined` in an node module called symbol-observables.

Does anyone have a clue what I might be doing wrong? 

Edit: I'm using the latest ng2-redux beta.

**Comment by SethDavenport** [comment]
This may be related to #228

**Comment by duydao** [comment]
The easiest way to get it up and running in ionic is to add the --dev param to the build script. See https://github.com/driftyco/ionic-cli/issues/1504

**Comment by e-schultz** [comment]
Just published a new beta.

Slight change with how you import the module, now should do `NgReduxModule.forRoot`,

[change-log details](https://github.com/angular-redux/ng2-redux/blob/master/CHANGELOG.md#using-ngreduxmodule)

**Comment by SethDavenport** [comment]
This should be fixed in 4.0.0-beta.7. Closing issue; feel free to reopen it if you still have issues with the new version of ng2-redux.
