### ISSUE TITLE
View does not refresh with Redux in Internet Explorer 10/11 

### ISSUE THREAD

**Issue by gnujeremie** [angular-redux/ng2-redux#233]
I will copy/paste what I submitted in https://github.com/angular/angular/issues/12307

**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am using redux/ng2-redux (https://github.com/angular-redux/ng2-redux) to save my application state. Some of the informations displayed in the application come from my redux state.
I have a weird behavior with IE 11 (and IE 10), and I don't know if it's a bug from angular, from redux, or from myself.

I use the async pipe to display the data from the state (because they are observables in my components) : 

```
export class MyComponent {
    @select('title') title$: Observable<any>;
}
```

and the html :

```
<h1>{{ title$ | async }}</h1>
```

When the title is update in my redux state, the view is not updated until I click anywhere in the page (in case you're wondering, the change detection strategy is the default one, not push).

I can force the update of the view when I run : 

```
this.ngRedux.subscribe(() => {
    this.zone.run(() => {
    });
});
```

**Expected behavior**
The view should be updated

**Please tell us about your environment:**
Virtual machines, windows 7 / 10
- **Angular version:** 2.1.0
- **Browser:** internet explorer 10/11
- **Language:** Typescript

**Comment by e-schultz** [comment]
@gnujeremie thanks for bringing this up - is this behavior happening in a small app (ie: fresh / no other stuff) - or do you have other midlware/etc going on?

**Comment by SethDavenport** [comment]
@gnujeremie do you have a repo we can try it out on?

Also, to help troubleshoot the issue:
1. what middlewares/store enhancers are you using (if any)?
2. what version of rxjs are you using?
3. what version of zonejs are you using?

Thanks

**Comment by gnujeremie** [comment]
Hello,

So I'm using rxjs 5.0.0-beta.12, zonejs 0.6.25. 
What do you mean by middleware/store enhancers ? Here's the dependecies from my package.json : 
```
  "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "angular2-datatable": "^0.4.2",
    "angular2-google-maps": "^0.15.0",
    "core-js": "^2.4.1",
    "dragula": "^3.7.1",
    "intl": "^1.2.5",
    "lodash": "^4.14.1",
    "ng2-dragula": "^1.2.1",
    "ng2-redux": "^4.0.0-beta.0",
    "ng2-translate": "^2.5.0",
    "redux": "^3.5.2",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.12",
    "socket.io-client": "^1.4.8",
    "zone.js": "0.6.25"
  },
```

I should try to reproduce it with a small app because it's not a very big one, but not a small one neither. :)

**Comment by bennett000** [comment]
@gnujeremie I have two more questions:

- Does the software behave as expected on browsers other than IE?
- How/where in your code are you `dispatch`ing to the store?

**Comment by gnujeremie** [comment]
Yes, everything is fine in FF/Chrome.

I am dispatching like : 
```this.ngRedux.dispatch({ type: ACTION, data: VALUES });``` (as said in the docs), from inside my components.

**Comment by gnujeremie** [comment]
I'll close this issue because I have this issue even without redux. Sorry for the inconvenience :)

**Comment by SethDavenport** [comment]
No worries, thanks for letting us know. One thing you might check is what polyfills your project is using - one idea might be to create an angular-cli test project and see what polyfills they use.

**Comment by san4ezz87** [comment]
Hellow I have the same issue and I think it's may be your mistake because async pipe doesen't work only with your selector in ie 10-11. When I work with async pipe without your selectors it's work well. Can you help me? I didn't see anything on stackOverflow about this issue.
