### ISSUE TITLE
Can't unsubscribe selected data

### ISSUE THREAD

**Issue by NagRock** [angular-redux/ng2-redux#240]
Hi, I got selector for chat messages on chat channel:

```
public getMessages(): Observable<ChatMessage[]> {
    return this.ngRedux.select((x: MyStore) => x.chat.channels[this.chatId].messages);
}
```

It works fine, but I can't unsubscribe it when chat channel is removed and get nullpointers.

Shouldn't be a unsubscribe method for select?

And also when component is removed, how garbage collector can remove my component if ngRedux still got reference to it?

**Comment by SethDavenport** [comment]
There's no subscription happening in the code you just posted, only a transformation. By itself that code will do nothing; you must be calling `subscribe` or `forEach` on the return value of getMessages() somewhere else (either that or you're using `| async` on it?).

There are two common ways to manage an observable subscription in a component.

Manual subscription:

```typescript
@Component({ 
  /*...*/
  template: '<div>{{ messagesValue }}</div>', // or whatever
})
class MyComponent {
  // Bind this into your template
  messagesValue: ChatMessage[];

  private subscription: Subscription;
  
  // get the observable and subscribe to it when the component is added
  // to the DOM:
  ngOnInit() {
    this.subscription = getMessages().subscribe(messages => {
      this.messagesValue = messages;
    });
  }

  // Unsubscribe when the component is removed from the DOM:
  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
```

Subscription managed by Angluar2's Async Pipe:

```typescript
@Component({ 
  /*...*/
  template: '<div>{{ messages$ | async }}</div>', // or whatever
})
class MyComponent {
  // Bind this into your template with | async
  messages$: ChatMessage[];
  
  // get an observable for | async to manage. AsyncPipe will subscribe for you when
  // the component is added to the DOM.
  ngOnInit() {
    this.messages$ = getMessages();
  }

  // AsyncPipe will unsubscribe for you when the component is removed from the DOM.
}
```

**Comment by NagRock** [comment]
I'm using async pipe but I do a delete on chat channel object.
