### ISSUE TITLE
Cleaning Up Observables Created By Select

### ISSUE THREAD

**Issue by nrgonzalez777** [angular-redux/ng2-redux#241]
Hello,

I was just curious to find out why when using the recommended "select" pattern for creating observables, there doesn't seem to be a need to dispose of said observables? When you use the "connect" pattern its your responsibility to unsubscribe from the observable when your component is destroyed, but from all the samples I've seen the observables created by select aren't unsubscribed from. How does this not cause a memory leak? Also, this question is not to insinuate that you are shipping code with a memory leak, I just haven't been able to figure it out on my own after perusing the source.

Thanks,

Nathan

**Comment by dagstuan** [comment]
Just using `select()` itself doesnt create a memory leak, it just exposes a slice of state as an observable, which can be subscribed to. Most of the examples do the actual subscribing in the template, with async pipes, such as `myObservableProp | async`. In this case the async pipe handles the subscribe and unsubscribe, and does not create a memleak. If you do the subscribing yourself however, you do need to keep track of the subscriptions and unsubscribe on component destroy. Do you have an example of code in the examples that create memleaks?

**Comment by nrgonzalez777** [comment]
No I don't have an example. This was just a theoretical question, and it turns out I didn't have a full understanding of how the async pipe worked. Thanks!
