### ISSUE TITLE
How to add an item to a nested Array?

### ISSUE THREAD

**Issue by windischb** [angular-redux/ng2-redux#244]
Hi!

Can anybody give me a hint on how to add an item to an Array which is a nested property?
For example:

```
export interface ILogging{
    Entries: Array<Object>;
}
export interface ILoggingRecord extends TypedRecord<ILoggingRecord>, ILogging{

}
export const LoggingFactory = makeTypedFactory<ILogging, ILoggingRecord>({
    Entries: new Array<Object>()
});
```

Which function can i use to add an entry to "Entries"?

```
export function LoggingReducer(state: ILoggingRecord = INITIAL_STATE, action: IPayloadAction): ILoggingRecord {

    switch (action.type) {
        case LoggingActions.ADDEntry:
            return state.????


        default:
            return state;
    }
}
```

**Comment by windischb** [comment]
For now i use this:
`return state.updateIn(["Entries"], (e: Array<Object>) => e.concat(action.payload));`
Is this the right way???
Because my view doesnt update every time i add an item...
Only if invoke ChangeDetectorRef.detectChanges().
Is this a normal behavior, and calling detectChanges() is necessary all the time when the Array changes?

**Comment by SeriousM** [comment]
> `return state.updateIn(["Entries"], (e: Array<Object>) => e.concat(action.payload));`
> Is this the right way???

it seems so 👍 

> Because my view doesnt update every time i add an item...
> Only if invoke ChangeDetectorRef.detectChanges().

how did you attach the view?
are you using the async pipe?

**Comment by windischb** [comment]
Yes is use 
```
<div *ngFor="let ev of events | async"> 
    <logentry [logEntry]="ev"></logentry>
</div>
```

The logging events comes from an signalr websocket connection.
so every time a event arrives the view should be updated.
It looks like the View is on event behind...
on the first event, nothing shows up,
on the second event, the first event is shown,
on the third event the first and second event shown up, but not the third.
only if i invoke ChangeDetectorRef.detectChanges(), everytime an event arrives, all entries are shown...

**Comment by SethDavenport** [comment]
> The logging events comes from an signalr websocket connection.

This makes me thing this is a zoneJS thing - not too familiar with signalr but I'm guessing you're doing a `store.dispatch` inside a callback from signalr? Such a callback would be outside the Angular zone and therefore may not trigger change detection reliably.

This is a fairly common issue when trying to integrate events from third-party libs into angular.

Can you post the code for your signalr event callback?  You might need to inject `NgZone` and wrap the dispatch in an `ngZone.run()`.

**Comment by SethDavenport** [comment]
If that works, please let me know; we might be able to smarted up `distpatch` in a future release (cc @e-schultz).

**Comment by windischb** [comment]
I'll create a simple example, based on my Problems, which includes SignalrR and ng2-redux to retrace the Problems...
As soon as the example is ready, i'll post the link to the repository!
Thanks for your help!

**Comment by windischb** [comment]
Example is ready -> [https://github.com/windischb/ng2-redux_SignalR](https://github.com/windischb/ng2-redux_SignalR)
The Problem with updating the UI is gone...
I don't know why it now works without invoking .detectChanges(), maybe there was any other issue in my productive code...
The main thing is it works now!
But the Problem from the other thread is still there!
In the example there are 6 Buttons.
2 for starting the SignalR connection,
2 for stopping the SignalR conneting,
and 2 for toggle the SignalR connection.
Every time you click on a "not working" button AT FIRST, it failes!

If the Signalr connection is established and you hit for example the URL http://localhost/api/status an LogEvent will be added an the screen.
But as mentioned before, this works now!

**Comment by SethDavenport** [comment]
Someone else reported on gittern an issue with updates when using Angular 2.1 and ZoneJS 0.6.17. When he updated to ZoneJS 0.6.21 (the version listed as a peer dep by @angular.core) it worked again. So I wonder if that's related: your new repo is using 0.6.23; what version was your old repo using?

Thanks for making the example - that's helpful. I'll take a look tonight.

**Comment by SethDavenport** [comment]
OK yeah so the 'invalid keypath' issue you're getting is caused by this code: https://github.com/windischb/ng2-redux_SignalR/blob/master/WebApiHtml/src/app/reduxstore/settings/settings.factory.ts#L6

Your typed-immutable-record is shallow, not deep.  So you're effectively ending up with a Record whose `SignalR` property is a raw Object;  `setIn` expects Immutable data structures all the way down which is why it's complaining.

You probably need to do something like this: 

```typescript
export const SettingsFactory = makeTypedFactory<ISettings, SettingsRecord>({
    // Where SignalRFactory is its own record type.
    SignalR: SignalRFactory({
        connect: true
    })
});
```

@danielfigueiredo does this makes sense?
