### ISSUE TITLE
Error importing when using angular-cli `ng serve`

### ISSUE THREAD

**Issue by miller-time** [angular-redux/ng2-redux#247]
The other day, I was able to load ng2-redux into an app with SystemJS. Today I'm trying out angular-cli and having problems.

 * installed ng2-redux and redux into the project with `npm install ng2-redux redux`.
 * tried to import `NgReduxModule` in my app.module.ts

```ts
import { NgReduxModule } from 'ng2-redux';
```

 * got some errors when running `ng serve`

```
ERROR in ./~/redux/lib/combineReducers.js
Module not found: Error: Can't resolve 'lodash/isPlainObject' in '/Users/rtmiller/projects/buddies/node_modules/redux/lib'
 @ ./~/redux/lib/combineReducers.js 8:21-52
 @ ./~/redux/lib/index.js
 @ ./~/ng2-redux/lib/components/ng-redux.js
 @ ./~/ng2-redux/lib/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/redux/lib/createStore.js
Module not found: Error: Can't resolve 'lodash/isPlainObject' in '/Users/rtmiller/projects/buddies/node_modules/redux/lib'
 @ ./~/redux/lib/createStore.js 7:21-52
 @ ./~/redux/lib/index.js
 @ ./~/ng2-redux/lib/components/ng-redux.js
 @ ./~/ng2-redux/lib/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in [default] /Users/rtmiller/projects/buddies/src/app/app.module.ts:6:9
Module '"/Users/rtmiller/projects/buddies/node_modules/ng2-redux/lib/index"' has no exported member 'NgReduxModule'.
```

I'm not super familiar with angular-cli, but it kinda looks like #237 might be related?

Or maybe I'm just missing a step somehow?

Environment Details:

```
~ • ng --version
angular-cli: 1.0.0-beta.19-3
node: 5.5.0
os: darwin x64

package.json:
...
"ng2-redux": "3.3.9",
"redux": "3.5.0",
```

**Comment by miller-time** [comment]
Update!

I was able to get past this error at last. I followed along with the commits [here](https://github.com/SethDavenport/thing) which was posted in #180 a few months ago. 

In the end all I really needed to do was change:

```ts
import { NgReduxModule } from 'ng2-redux';
// ...
  imports: [ NgReduxModule ]
// ...
```

to:

```ts
import { NgRedux } from 'ng2-redux';
// ...
  providers: [ NgRedux ]
// ...
```

I guess I'll just watch for a release that incorporates #237 in order to be able to import `NgReduxModule`?

**Comment by e-schultz** [comment]
Have you tried the v4 beta of ng2-redux? noticed "ng2-redux": "3.3.9" in your environment details above.

**Comment by SethDavenport** [comment]
Specifically, `npm install --save ng2-redux@4.0.0-beta.7` should do the trick.

I have a sample repo where I have successfully used ng2-redux and the angular-cli here: https://github.com/SethDavenport/ng2-redux--with-aot

**Comment by miller-time** [comment]
@e-schultz / @SethDavenport thanks, works perfect!
