### ISSUE TITLE
deprecate 'connect' pattern?

### ISSUE THREAD

**Issue by SethDavenport** [angular-redux/ng2-redux#250]
Currently ng2-redux supports the react-redux-style 'connect' pattern and the angular2-style 'select-observable' pattern.

Our experiments with the connect pattern indicate that it just doesn't perform well with Angular2's change detection and rendering strategies and is a bad fit for the framework.

Since the 'select' pattern is by far the recommended approach, deprecating the 'connect' pattern in 4.x and removing it completely in 5.x would allow us to drop a large chunk of code.

**Comment by SethDavenport** [comment]
That said, I'm interested in feedback from the community - feel free to post in this issue.

**Comment by spock123** [comment]
I say: deprecate the 'connect' pattern.

**Comment by SethDavenport** [comment]
Deprecated in 4.2.5, removed in 5.0.0-beta.1.
