### ISSUE TITLE
 Error: No provider for DevToolsExtension! at NoProviderError.BaseError [as constructor]

### ISSUE THREAD

**Issue by ryandepalma** [angular-redux/ng2-redux#251]
Noticed this error in my console after updating from the 4.0.0 beta to the 4.0.0 release.

I went ahead and added DevToolsExtension to my AppModule's providers array...error went away

Just wanted to check that was the expected resolution as the docs around integrating the chrome redux dev tools extensions didn't mention anything that added step??

**Comment by SethDavenport** [comment]
Yes that's the correct resolution for now.  We will expose it as an importable module shortly.

**Comment by SethDavenport** [comment]
I will release a fix for this soon - it will be exported from `NgReduxModule.forRoot()` along with `NgRedux` itself.

**Comment by SethDavenport** [comment]
Can you try ng2-redux@4.1.0? Should be fixed now. Sorry about that.

**Comment by ryandepalma** [comment]
yep, that fixed it :)
