### ISSUE TITLE
No provider for NgRedux!

### ISSUE THREAD

**Issue by JesterXL** [angular-redux/ng2-redux#253]
I get this error in 4.1.0. If I go back to beta.0, it goes away.

**Comment by SethDavenport** [comment]
Can you share your NgModule initialization code?

**Comment by SethDavenport** [comment]
Did this help resolve your issue?

**Comment by SethDavenport** [comment]
Closing. Feel free to re-open if you're still having problems.

**Comment by JesterXL** [comment]
Thanks @SethDavenport, updated this morning, and apparently our code was missing the `NgReduxModule.forRoot()`. We didn't have the forRoot() method being called in the imports.

**Comment by SethDavenport** [comment]
Sounds good. The forRoot stuff was added in later betas to support AoT
