### ISSUE TITLE
Migration from ngRedux 1

### ISSUE THREAD

**Issue by gseerden** [angular-redux/ng2-redux#256]
Hi,

I have an Angular 1.5.x application which uses ngRedux. About the migration to Angular 2 and ngRedux 2,  is it possible to have both libraries share the same store? Do you have tips to make the migration as smooth as possible?

Thanks

**Comment by SethDavenport** [comment]
Yes both libs should be able to share the same store. For ng2-redux, instead of calling NgRedux.configureStore, instead use `NgRedux.provideStore()` with the store you passed to NgRedux 1.

**Comment by SethDavenport** [comment]
As for tips - I haven't actually done this type of migration but IIRC NgRedux 1 is based on the 'connect pattern' (mapStateToThis, mapDispatchToThis, etc).

While Ng2Redux also supports this, I recommend taking the opportunity to move over to the NgRedux.select() pattern which is based on Observable state slices instead.  This is more efficient for ng2 because it fits better with ng2's change detection approach.

**Comment by SethDavenport** [comment]
But yeah let me know how it goes - I'd like to roll your feedback into a potent migration guide.

**Comment by gseerden** [comment]
Thanks @SethDavenport. I'll let you know how this goes.

**Comment by gseerden** [comment]
Hi Seth, I finally got some time to tackle this migration. I have an AngularJS module where I set up $ngRedux. Then I used `upgradeNg1Provider` to make it injectable in Angular2+. 

```JS
const myApp = angular
  .module('myApp', [ngRedux])
  .config(($ngReduxProvider) => {
    $ngReduxProvider.createStoreWith(rootReducer, []);
  });
adapter.upgradeNg1Provider('$ngRedux');
```

Then in my module's constructor, I use `provideStore` like you mentionned. 

```JS
export class AppModule {
  constructor(ngRedux: NgRedux<IAppState>, @Inject('$ngRedux') store) {
     ngRedux.provideStore(store);
  }
}
```

But then I run into the following error: `TypeError: object is not observable`. Do you have any idea of what I'm doing wrong?

**Comment by gseerden** [comment]
It seems that ng-redux and ng2-redux stores are not compatible because ng-redux removes the property `[$$observable]` from the store object. 

https://github.com/angular-redux/ng-redux/pull/129
