### ISSUE TITLE
How can i get the current value from the store?

### ISSUE THREAD

**Issue by windischb** [angular-redux/ng2-redux#257]
Hi!

I have an Array of objects stored in the store.
Now i have the get one Item from this Array.
Whats the best way to get the current Array from the store, to find then the item which is needed?

In my case the Array is used for a list of items in the view.
If the users click on the edit button, the user will be rerouted to a new page with the item id in the Url.
And on this new Page i would like to pull the item with this Id from the store to prefill a form...

```
ngOnInit() {
        this.route.params
            .map(params => params['id'])
            .subscribe((id) => {
                if (id == "new") {
                    this.action = "newEndpoint";
                } else {
                    this.action = "updateEndpoint";
                    var endpoints = this.ngRedux.getState().EndpointMgmt.EndPoints;
                    this.endpoint = endpoints.find(endp => endp.id == id);
                }
            });
    }

```

**Comment by SethDavenport** [comment]
Probably best to use our gitter channel for non-bug questions like this: https://gitter.im/angular-redux/ng2-redux

**Comment by SethDavenport** [comment]
However in your case I'd probably do something like (not tested):

```typescript
@Component({...})
class FooComponent {
  ngOnInit() {
    this.route.params
      .map(params => params.id)
      .mergeMap(ngRedux.select(['EndpointMgmt', 'Endpoints']))
      .find(endp => endp.id === id)
      .subscribe(endp => {
        this.action = endp ? 'updateEndpoint' : 'newEndpoint';
        this.endpoint = endpoint;
      });
  }
}
```

**Comment by SethDavenport** [comment]
One other thing I might do differently is avoid storing the list in the store as an array, but instead as an object indexed by id.

So instead of this:

```ts
[
  { id: 'id1', /* other properties */ },
  { id: 'id2', /* other properties */ },
  // ...
]
```

This:

```ts
{
  'id1': { ordinal: 0, /* other properties },
  'id2': { ordinal: 1, /* other properties },
  // ...
}
```

That way you don't have an order-n lookup to match the endpoint every time.  When you need to display all of the endpoints as a list you can use a selector to transform it.
