### ISSUE TITLE
Support using constructor property types only, instead of @Inject

### ISSUE THREAD

**Issue by tracker1** [angular-redux/ng2-redux#26]
I wrote a wrapper using your connect, inside my own `store.js` file...

```
...
import Connector from 'ng2-redux/lib/components/connector'

export function Store(reduxStore) {
  const __connector = new Connector(reduxStore);
  return {
    ...reduxStore,
    connect: __connector.connect
  };
}
...
export function createStore() {
  ...
  return Store(createStoreWithMiddleware(reducer, state));
}
```

Then in my `index.js` ...

```
import {Store, createStore} from './store';
...
bootstrap(App, [
  provide(Store, { useValue: createStore() }),
  ...
]);
```

This way, in my components, I only need `constructor(store:Store)` to get the store reference, which works with babel/es6 as well as the preferred use for ng2.

Yes, it's explicit and one step removed from the provider, however, it allows for easier integration at the component level... not sure if the provider itself could be changed to support a type reference, but it would be nicer than poluting my constructors with `@Inject`

----

Maybe if you separated `Connector`, and its' dependencies into an `ng2-redux-connector` module, so it can be used more easily?  Either with the `provider` method this module uses, or the more explicit method I used.

**Comment by lanocturne** [comment]
+1

Michael J. Ryan <notifications@github.com>於 2016年3月8日 週二，下午12:00寫道：

> I wrote a wrapper using your connect, inside by store.js file...
>
> ...
> import Connector from 'ng2-redux/lib/components/connector'
>
> export function Store(reduxStore) {
>   const __connector = new Connector(reduxStore);
>   return {
>     ...reduxStore,
>     connect: __connector.connect
>   };
> }
> ...
> export function createStore() {
>   ...
>   const store = Store(createStoreWithMiddleware(reducer, state));
>   ...
>   return Store(store);
> }
>
> Then in my index.js ...
>
> import {Store, createStore} from './store';
> ...
> bootstrap(App, [
>   provide(Store, { useValue: createStore() }),
>   ...
> ]);
>
> This way, in my components, I only need constructor(store:Store) to get
> the store reference, which works with babel/es6 as well as the preferred
> use for ng2.
>
> Yes, it's explicit and one step removed from the provider, however, it
> allows for easier integration at the component level... not sure if the
> provider itself could be changed to support a type reference, but it would
> be nicer than poluting my constructors with @Inject
> <https://github.com/Inject>, which iirc, doesn't work via babel
> extensions outside typescript.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbuchwalter/ng2-redux/issues/26>.
>
-- 
Thanks,
Stanislaus

**Comment by e-schultz** [comment]
@tracker1 We are working on some changes for the next major release, and we will include something like this. Thanks for the input/code - much appreciated.

**Comment by e-schultz** [comment]
can also use an [OpaqueToken](https://angular.io/docs/ts/latest/api/core/OpaqueToken-class.html)

**Comment by e-schultz** [comment]
@tracker1 getting ready to have a new release available soon that will support property injection instead of needing `@Inject`, sorry for the delay on getting this out.

**Comment by SethDavenport** [comment]
@e-schultz is this fixed by 2.2.3?

**Comment by SethDavenport** [comment]
As of release 2.2.3 you can now do:

```typescript
class FooComponent {
  constructor(private ngRedux: NgRedux) {}
}
```

**Comment by tracker1** [comment]
Cool... no longer working on the app in question, but nice to see the feature just the same.  Really do like working with Redux over the "angular way" of services, etc...
