### ISSUE TITLE
How to prevent async databound lists to be non-flickeing if animated

### ISSUE THREAD

**Issue by obiwan007** [angular-redux/ng2-redux#261]
If I have a list inside my state which gets updates via add/remove actions.
This list is bound to my UI via @select.
If I add an element my list is cloneDeep'ed with lodash, added/removed the element and assigned back to the state.
In this moment the templete redraws the list (*ngFor) - but if I have an Animation attached to the itementry - the Animation will be triggered for all Elements - as they all look new to the databinding engine inside ng.

Is there a better approach to bind elements? 
Should I create a backing list in my component and only update it in a more inteligent way based on the subscription to state?
Or is my state updating to granular and should just update the list more global (not on add/remove level)?

**Comment by obiwan007** [comment]
I created a Little List Collection class for creating a subscription on the @select element. Updating added and removed items will be put on a backing array. This is not perfect as for more nested lists it is not working so far. Only toplevel items are used for comparison/injection so far.

Not perfect but better then nothing. Maybe doing a more deep inspections might help.

`export class ObservableCollection<T>{
  public data: T[] = new Array<T>();
  private subscription: any;

  comperator = (it1, it2) => {
    if (this.key) {
      return it1[this.key] === it2[this.key];
    } else {
      return JSON.stringify(it1) === JSON.stringify(it2);
    }

  }
  /**
   *
   */
  constructor(private observable: Observable<T>, private key: string = null) {
    this.subscription = observable.subscribe((d: T) => {
      let removed = _.differenceWith(<any>this.data, d, this.comperator);
      let added = _.differenceWith(<any>d, this.data, this.comperator);
      added.forEach(addedEntry => {
        this.data.push(addedEntry);
      });
      removed.forEach(rem => {
        let idx = this.data.indexOf(rem);
        if (idx > -1) {
          this.data.splice(idx, 1);
        }
      });
    });
  }

  unsubscribe() {
    this.subscription.unsubscribe();
  }
}`

**Comment by SethDavenport** [comment]
HI @obiwan007 

Have you tried using `trackBy` to help Angular determine what items are new? By default ngFor will look at references so it thinks everything is new. But you can supply a custom function instead: https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html

Scroll down to the section called 'Change Propagation'.

**Comment by obiwan007** [comment]
Hey, thx. That solved the Problem in a way more elegant way.
Completely missed that option...

**Comment by SethDavenport** [comment]
Awesome :)
