### ISSUE TITLE
install step missing redux

### ISSUE THREAD

**Issue by rajinder-yadav** [angular-redux/ng2-redux#270]
We should add,

```
npm install --save redux
```

So I don't have to see this error, because it not obvious from the readme?
![redux-error](https://cloud.githubusercontent.com/assets/439226/20856078/fb860fe4-b8d4-11e6-80f2-c96f137030e0.png)

**Comment by SethDavenport** [comment]
Should be obvious from knowing how `npm` works :)

But it's better to be clear, I agree. I've merged related PR #271 .
