### ISSUE TITLE
Error: No provider for DevToolsExtension when using Angular2-Universal

### ISSUE THREAD

**Issue by dguisinger** [angular-redux/ng2-redux#272]
I'm using server-side rendering through an ASP.NET JavaScriptServices for faster initial page loads.

It utilizes a server-side copy of NodeJS and Angular2 running with Angular2-Universal.

When running server side, some of the Angular2 modules such as browser aren't available, I'm assuming this could be tripping up the DevToolsExtension feature.

I'm getting the following error message when my application component attempts to initialize.
Error: No provider for DevToolsExtension

The only way I've found for the server side to initialize and pre-render is to comment out all of the DevToolsExtension code, which leaves me flying blind when working on my project.

I'm not too familiar with the life cycle of objects when things transition from server side pre-rendering to client-side, I imagine there must be a way to make this work.

Related projects:
https://github.com/aspnet/JavaScriptServices
https://github.com/angular/universal

Angular2-Universal "Gotchas":
https://github.com/angular/universal#universal-gotchas

**Comment by SethDavenport** [comment]
`DevToolsExtension` has some code to detect if `window` is available, so it should work. Normally that provider error happens when there's something funky happening at the app's `NgModule` level.

What version of ng2-redux are you using? Can you post your app's ngModule initialization code?

**Comment by dguisinger** [comment]
Its weird because its acting like the module doesn't exist when its trying to provide it during injection.  The code worked fine before I switched to using server-side pre-rendering.

Here's my code, i pulled out my long list of imports and declarations for my app since it was quite long:
```
import { NgModule } from '@angular/core';
import { UniversalModule } from 'angular2-universal';
import { Ng2BootstrapModule } from 'ng2-bootstrap/ng2-bootstrap';
import { NgReduxModule } from 'ng2-redux';

import { AppComponent } from './components/app.component';
import { AppLayoutComponent } from './components/app.layout.component';
import { routes,PageInitializationService } from './app.routing';
import {RouterModule, Router} from '@angular/router';
import { NgRedux, DevToolsExtension } from "ng2-redux";

import { AppState, default as reducer} from './reducers/index'
import { AppStore } from './app-store'

@NgModule({
    bootstrap: [AppComponent],
    imports:
    [
        UniversalModule, // Must be first import.  This automatically imports BrowserModule, HttpModule, and JsonpModule too.
        RouterModule.forRoot(routes), Ng2BootstrapModule,
        NgReduxModule.forRoot()],
    declarations: [AppComponent, AppLayoutComponent,
        ...],
    providers: [NgRedux, PageInitializationService]
})
export class AppModule {
    constructor(
    ) {
        
    }
}
```

and just to show how I was initializing the dev extensions:
```
import { Component, Inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import {AppLayoutComponent} from './app.layout.component';
import {NgRedux, DevToolsExtension } from 'ng2-redux'
import {PageInitializationService} from '../app.routing'
import * as CircularJSON from 'circular-json';

import { AppState } from '../reducers/index'
import { AppStore } from '../app-store'

import * as Actions from '../actions/index'


const __DEVMODE__ = true;

@Component({
    selector: 'app',
    template: `<app-layout></app-layout>`
})
export class AppComponent {
    constructor(private ngRedux: NgRedux<AppState>,
        pageInitializationService: PageInitializationService,
        private devTools: DevToolsExtension,
        private activatedRoute: ActivatedRoute) {

        let enhancers = [];
        // ... add whatever other enhancers you want.

         You probably only want to expose this tool in devMode.
        if (__DEVMODE__ && devTools.isEnabled()) {
            enhancers = [...enhancers, devTools.enhancer()];
        }

        this.ngRedux.configureStore(rootReducer,
            initialState, null,
            //[reduxLogger()],
            enhancers);
    }
} ```

**Comment by dguisinger** [comment]
Oh yeah, and I'm using:
Angular 2.0.0    (There appears to be an issue with Angular2-Universal if I use anything newer than 2.1.0 so I set my version numbers back for now)
Angular2-Universal 2.0.10
ng2-redux 4.1.0

**Comment by SethDavenport** [comment]
Huh that's strange. I haven't had the chance to play with universal myself.

It's curious to me that you've added `NgRedux`, but not `DevToolsExtension` to your `@NgModule` `providers` array. My understanding is that you shouldn't need either, because the `@NgModule` `import: [ NgRedux ]` should take care of it.

It's possible my understand of that is wrong though - can you try adding `DevToolsExtension` to your providers as well?

**Comment by dguisinger** [comment]
Odd, I could have sworn I tried that before.   I tried it again, and everything appears to work just fine.
