### ISSUE TITLE
Generated .js in lib does not correspond to .ts file in src (npm version 4.2)

### ISSUE THREAD

**Issue by AurelieV** [angular-redux/ng2-redux#281]
I have the problem of DevToolExtensions missing when I install the lastest version of the repo.
If I look at the src/ directory the fix is here, but the corresponding .js file in lib folder does not contain it.
Lib does not seems to contain the new version of the module. Everything is fine with version 4.1 in npm

**Comment by SethDavenport** [comment]
It appears to be working for me - can you share the specific error message you're getting?

**Comment by AurelieV** [comment]
The error is "No provider for DevToolsExtension".
If I console.log the result of .forRoot() method, it only return one element, and no providers.
If I look on my node_modules, in ng2-redux/src, the fix #252 is present. If I look at lib folder, it is not.

**Comment by SethDavenport** [comment]
@AurelieV Please try 4.2.1 - 4.2.0 was a botched publish on my part.
