### ISSUE TITLE
No more forRoot method in NgReduxModule

### ISSUE THREAD

**Issue by dalibor983** [angular-redux/ng2-redux#284]
In version 4.2.2 there is no more `forRoot` method in NgReduxModule.

Documentation says that we need to use `forRoot` method to import NgReduxModule.

Is documentation not updated for version 4.2.2 or something is wrong in NgReduxModule?

**Comment by SethDavenport** [comment]
Hmm looks like we need to update the docs. @e-schultz is that correct?

**Comment by obiwan007** [comment]
I'm getting alot of errors if I just remove forRoot(). Are there any other breaking changes introduced in the new version?

**Comment by e-schultz** [comment]
I'll look into it this weekend. I'll publish a version that brings forRoot back in the 4.x  - dropping it is a breaking change and should have been a new major version

**Comment by e-schultz** [comment]
rolled back the change for now - jumped the gun on the publish, sorry for the inconvinence.

**Comment by SethDavenport** [comment]
This has been fixed in our v5.x branch.  Give `5.0.0-beta.0` a try and let me know. We've updated the Angular peer dependency to 2.4.1 as well.
