### ISSUE TITLE
Changelog not updated for version > 4.2.1

### ISSUE THREAD

**Issue by oferh** [angular-redux/ng2-redux#287]
Descriptions of versions `4.2.2` and `4.2.3` are missing.

**Comment by 11mb** [comment]
It seems to me that the rollback for issue 284 has failed

**Comment by SethDavenport** [comment]
Yup busted :)

It has been updated. We'll do a better job of keeping it up to date going forward.

**Comment by oferh** [comment]
@SethDavenport we are here to catch that ;-)
Thanks for the fixes and continue the great work you're doing here
