### ISSUE TITLE
ng2-redux and systemjs

### ISSUE THREAD

**Issue by maufarinelli** [angular-redux/ng2-redux#297]
Hi, 

I am following all the Quick Start instructions, but I had 404 for redux and ng2-redux. 
So, in systemjs.config, maps, I added: 
```
'redux':        'npm:redux/dist/redux.js',
'ng2-redux':    'npm:ng2-redux/lib/index.js'
```
Now I have 
```
404 GET /node_modules/ng2-redux/lib/components/ng-redux
404 GET /node_modules/ng2-redux/lib/components/dev-tools
404 GET /node_modules/ng2-redux/lib/decorators/select
404 GET /node_modules/ng2-redux/lib/ng-redux.module
```

Wha am I missing?

Thanks a lot

**Comment by SethDavenport** [comment]
I got it working with systemJS a while ago: https://github.com/SethDavenport/ng2-redux-systemjs-example

However I haven't tried with recent versions of Angular or NgRedux.

Just a caveat: most of the Angular community has coalesced around webpack.

If you go with SystemJS you're likely in for a lot of pain getting bundling, ahead-of-time compilation, etc. working. Note that none of this is specific to ng2-redux. SystemJS makes consuming libs with transitive dependencies unnecessarily difficult; combine this with the complexity of the Angular toolchain and you may be in for a rough time.

If you're able to start fresh, the easiest way to get set up is probably to use the Angular CLI (which is based on webpack).

**Comment by maufarinelli** [comment]
Yes, you are right. SystemJS make things unnecessary difficult, but I started on top of Angular QuickStarter which is based on SystemJS.

I will probably change it. But maybe more people will aks you about, due to QuickStarter

**Comment by SethDavenport** [comment]
OK yeah our system JS example needs updating to capture the latest changes to the Angular quickstart stuff.  I'll update it soon.

**Comment by maufarinelli** [comment]
Thanks Seth, it will be great.  

However, I took your advice and I am changing my app to use angular-cli. I think it be better for the future.

Thanks a lot

**Comment by SethDavenport** [comment]
Ok thanks.

FWIW the updated example is here: https://github.com/angular-redux/system-js-example

But IMO you're much better off with the angular-CLI :)
