### ISSUE TITLE
Get the store as Observable

### ISSUE THREAD

**Issue by jiayihu** [angular-redux/ng2-redux#299]
Is there any way to get the store/complete state as an Observable? Currently `ngRedux.getState()` returns the application state as `redux` does and not as an Observable.

[ngrx/store](https://github.com/ngrx/store/blob/master/src/store.ts) has the store as Observable by default, so you can subscribe it directly if you want to do something like persistence in localStorage.

For now, I solved it myself writing an utility which wraps `subscribe` in an Observable:
```typescript
import { Observable } from 'rxjs/Observable';
import { NgRedux as Store } from 'ng2-redux';

export default function observableStore<T>(store: Store<T>): Observable<T> {
  return Observable.create(observer => {
    observer.next(store.getState());

    const dispose = store.subscribe(() => {
      observer.next(this.store.getState());
    });
    return dispose;
  });
};
```

**Comment by SethDavenport** [comment]
Currently not directly.  For now, you can achieve the same effect using an identity function as the argument:

```typescript
  constructor(ngRedux: NgRedux) {
    this.store$ = ngRedux.select(s => s);
  }
```

It would be nicer to make `ngRedux.select()` with no args return the root observable.  I'll look to make that change in an uncoming release.

**Comment by jiayihu** [comment]
Thanks, your solution is a much simpler alternative. 
Adding the support for `ngRedux.select()` should be trivial like `if (selector === undefined) result = this._store$` [here](https://github.com/angular-redux/ng2-redux/blob/feat/v5/src/components/ng-redux.ts#L135) I believe. I could make a PR if my assumption is right.

**Comment by SethDavenport** [comment]
Yup. I was actually thinking of simply changing line 134 to read:

```typescript
let result = this._store$;
```

If you have time to make a PR that would be awesome.

**Comment by SethDavenport** [comment]
Will release in 5.1.

**Comment by jiayihu** [comment]
@SethDavenport Thank you very much for your support! I'll wait for the release (:
