### ISSUE TITLE
Warning on missing source file

### ISSUE THREAD

**Issue by alexthewilde** [angular-redux/ng2-redux#311]
I get this warning after a fresh npm install:

> WARNING in ./~/ng2-redux/lib/ng-redux.module.js
Cannot find source file '../src/ng-redux.module.ts': Error: Can't resolve '../src/ng-redux.module.ts' in './node_modules/ng2-redux/lib'
 @ ./~/ng2-redux/lib/index.js 8:24-52
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

Checking the files under `src`, there's actually no `ng-redux.module.ts`.

**Comment by e-schultz** [comment]
@alexthewilde which version are you trying to install? I Just pushed a fix in the 3x branch - NgModule wasn't supported yet in that one and there was no ng-redux.module, just pushed 3.1.11 - let me know if you still have the issue.

**Comment by alexthewilde** [comment]
@e-schultz ng2-redux was at `3.1.10`. `3.1.11` made the warning go away. I'm getting new warnings now though for `ng2-redux-router`:

> WARNING in ./~/ng2-redux-router/lib/esm/router.js
Cannot find source file '../../src/router.ts': Error: Can't resolve '../../src/router.ts' in '../node_modules/ng2-redux-router/lib/esm'

(in total 4 warnings). `ng2-redux-router` is at `2.0.0`.

**However**: installing the libs in a fresh angular cli installation brings up no warnings whatsoever. So I assume it's gotta be related to my project env. I'll investigate this further.

Meanwhile could you explain the difference the 3.x and 5.x branch, are there any docs? I guess for any project 5.x is recommended right?

Thanks.

**Comment by SethDavenport** [comment]
There is the changelog in the repo. However the main differences are 

1) an API change to make our NgModule import cleaner, and
2) we removed the deprecated `connect` pattern from the API since the `select` pattern is now the recommended approach with angular.

**Comment by SethDavenport** [comment]
Are we ok to close this or are you still having trouble?
