### ISSUE TITLE
Updating to ^5.1.0 broke the observables emitting events after the first one

### ISSUE THREAD

**Issue by anton-107** [angular-redux/ng2-redux#316]
Hi guys,
my app stopped working after upgrading to 5.1.x

At first, i thought i was having this issue: https://github.com/angular-redux/ng2-redux/issues/259

After closer look, I saw, that observables that i get with `@select` are working but they emit only the first event (so .subscribe(x => { console.log(x);} ) will log only once. Downgrading to `ng2-redux` fixed this issue. Am i missing some breaking change in `ng2-redux`?

Dependencies in package.json:
```
"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "ng2-redux": "^5.1.2",
    "redux": "^3.6.0",
    "redux-logger": "^2.8.1",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  }
```

**Comment by e-schultz** [comment]
There was a change done so that changes only get emitted if the state actually changes (ie: if you fire an action that doesn't cause a state change).


```js
let someReducer(state, action) => {
   switch(action.type) {
       case 'HANDLED' : return Object.assign({},state, { someModification: action.payLoad })
       default: return state;
   }
}

//

ngRedux.dispatch({type: 'HANDLED'}) // modifies state - subscribers should get called
ngRedux.dispatch({type: 'SOME_OTHER_TYPE'}) // if this doesn't modify state, then the subscribers don't get called
```

Is there a possibility that you have a reducer that is mutating state instead of returning a new copy?

**Comment by anton-107** [comment]
@e-schultz: yes, i'm changing the state but not doing a new copy of the object. Thank you for the explaination
