### ISSUE TITLE
DI For Middleware

### ISSUE THREAD

**Issue by e-schultz** [angular-redux/ng2-redux#41]
ng-redux for Angular 1 supports DI for middleware, would like to get the same functionality here.

Prior art/other examples:
[ngrs/Store and how they handle middleware](https://github.com/ngrx/store/blob/master/src/ng2.ts)
[angular2-redux](https://github.com/InfomediaLtd/angular2-redux/blob/master/src/app-store-factory.ts) - although don't think this lets middleware use DI
[ng-redux](https://github.com/angular-redux/ng-redux/blob/master/src/components/ngRedux.js#L41)

Thinking so we can still keep with the provide(store), maybe something like:

```js
import { provide, createStoreWith } from 'ng2-redux'

let store = createStoreWith(reducer,middleware,storeEnhancer, initialState)
bootstrap(App,provide(store));
```

or

```js
import thunk from 'redux-thunk'
import someProviderMW from 'some-provider-mw'

let store = createStoreWith(reducer,[thunk,someProviderMW])
bootstrap(App,provide(store));
```

Then - if the middleware is just a function - push it into the middleware array, if the middleware is an instance of a provider - use the injector to create an instance of it, then push it onto the middleware collection.

use case: making a middleware that needs access to Angular's HTTP service,

**Comment by SethDavenport** [comment]
So ngrx and redux middlewares are actually quite differerent.  Ngrx lets you add 'pre' and 'post' middlewares, and they appear to be similar to RxJS operators: `(observable: Observable) => Observable`

Redux middlewares are in practice essentially curried versions of `(store, next, action) => action`

Nonetheless, I like ngrx's idea of providing a 'createMiddleware' convenience function to handle the DI if needed.  Taking a look at what that would entail. The signature would be something like:

```typescript
type <S>createMiddleware(middleware: Middleware<S>, providers: Provider[]): Middleware<S>
```

**Comment by SethDavenport** [comment]
In that case you could do:

```typescript
import thunk from 'redux-thunk'
import someMwWithDiDependencies from 'some-mw'

let store = createStoreWith(reducer,[thunk,createMiddleware(someMwWithDiDependencies)])
bootstrap(App,provide(store));
```

**Comment by SethDavenport** [comment]
Looking into it more I don't think we can do this without wrapping `applymiddleware`.

The reason is that we're currently applying middleware functions at boot time, before the injector has been created.  However in order to go from a middleware factory function that takes injectable arguments, we need to have an injector.  So it's a chicken and egg problem.

Really the sequence needs to be:
1. register providers for middlewares than need DI with Angular
2. register these mw factories also with ng2-redux
2. bootstrap the app
3. after bootstrap, have ng-redux run through it's list of mwFactories and convert them in to middlewares, and apply them to the store.

The way redux works, we'll start to go down a rabbit hole of delaying store configuration until after bootstrap as well, which is a pretty large change.

I think we need to delay this one until post release.

**Comment by SethDavenport** [comment]
NgRedux gets away with it because they wrap pretty much everything; applyMiddleware is no longer part of store configuration - you can call usePreMiddleware and usePostMiddleware after the fact.

Since they also hold references to their middle wares they can fiddle with the injection later as well.

Since we actually don't wrap the store config and middleware application at all, but use the vanilla redux stuff our flexibility is limited.  If we could somehow separate provide(store) and middleware application we'd be in business.

**Comment by SethDavenport** [comment]
We _could_ do something like:

```typescript
import { Middleware } from 'redux';
import { RandomNumberService } from '../services/random-number';
import { Injector } from 'angular2/core';

const inj = Injector.resolveAndCreate([RandomNumberService]);

export const diMiddleware = store => next => action => {
  const rns = inj.get(RandomNumberService);

  console.log('Pre-number:', rns.pick());
  const result = next(action);
  console.log('Post-number:', rns.pick());
  return result;
};
```

But it's not clear how this fits into the injector tree.  I think it creates a new one. This could lead to things that are supposed to be singletons not being any more.

Also I'm not really sure how you'd test this.

**Comment by SethDavenport** [comment]
Another alternative would be to make ngRedux` @Injectable` and only talk to redux through it.

But in this case, we'd bootstrap like this:

```typescript
bootstrap(App, [ NgRedux, ... ]
```

And then delay all the configure store stuff to the App component:

```typescript
@Component({
  ...
})
class App {
  constructor(private ngRedux: NgRedux) {
    ngRedux.createStore(reducers, middlewares, enancers, initialState);
  }
}
```

In this case createStore would do the actual redux stuff on our behalf, and would at this point have the ability to intercept middlewares whose dependencies need resolving and resolve them first before passing them to redux.

However this would likely not be backward compatible (unless we can keep the only init strategy around too, maybe with a deprecation warning).

**Comment by SethDavenport** [comment]
This way, the store isn't directly injectable - you'd have to inject ngRedux and call .getStore() or similar.

**Comment by SethDavenport** [comment]
It would also complicate an @Select implementation somewhat, although we already have DI issues with that.

**Comment by SethDavenport** [comment]
Clearly this needs some discussion.  In the interim, I've provided a README example for how this can be done with the current beta.

**Comment by SethDavenport** [comment]
https://github.com/angular-redux/ng2-redux/pull/49

**Comment by SethDavenport** [comment]
Another option is to get rid of `provide(store)` and ngRedux's constructor param and instead provide an `ngRedux.setStore()` method.

This way we can construct the store and provide the middlewares after the DI has bootstrapped, most likely in the app's root component:

```typescript
@Component({
  // ...
})
class App {
  constructor(
    private ngRedux: NgRedux<IAppState>,

    ngRedux.setStore(configureStore({}));
  );
}
```

__Pros:__
* Nothing else changes in the ngRedux API.
* Simple to implement.
* At this point we can use injection wherever we feel like it: middlewares, enhancers, etc.
* Everything inside ngRedux can use angular services if needed - this opens the way for ngZone devtool fixes, etc.

__Cons:__
* Breaks backwards compatibility: we'd need to do a major version bump.
* Need to think through what the effect is on a potential `@Select` implementation.
* Nothing preventing someone from calling setStore twice - we'll need to guard against that.

@Select would likely need to create an empty observable and register it with ngRedux global state somehow.  When setStore() gets called, we'd need to hook chain the empty observable up to an actual observable.

Also not clear when these global refs would get cleaned up?
