### ISSUE TITLE
Warnings displayed by webpack when using source-map-loader 

### ISSUE THREAD

**Issue by TobiasKrogh** [angular-redux/ng2-redux#64]
Hey,

just a minor thing. Might not even be worth mentioning it in the README. When using the [source-map-loader](https://github.com/webpack/source-map-loader) to extract source maps without any excludes ng2-redux 2.2.3 displays warnings.

```bash
WARNING in ./~/ng2-redux/lib/index.js
Cannot find source file '../src/index.ts': Error: Cannot resolve 'file' or 'directory' ../src/index.ts in /vagrant/styleguide/node_modules/ng2-redux/lib

WARNING in ./~/ng2-redux/lib/components/provider.js
Cannot find source file '../../src/components/provider.ts': Error: Cannot resolve 'file' or 'directory' ../../src/components/provider.ts in /vagrant/app/node_modules/ng2-redux/lib/components

WARNING in ./~/ng2-redux/lib/components/ng-redux.js
Cannot find source file '../../src/components/ng-redux.ts': Error: Cannot resolve 'file' or 'directory' ../../src/components/ng-redux.ts in /vagrant/app/node_modules/ng2-redux/lib/components

WARNING in ./~/ng2-redux/lib/utils/shallowEqual.js
Cannot find source file '../../src/utils/shallowEqual.ts': Error: Cannot resolve 'file' or 'directory' ../../src/utils/shallowEqual.ts in /vagrant/app/node_modules/ng2-redux/lib/utils

WARNING in ./~/ng2-redux/lib/utils/wrapActionCreators.js
Cannot find source file '../../src/utils/wrapActionCreators.ts': Error: Cannot resolve 'file' or 'directory' ../../src/utils/wrapActionCreators.ts in /vagrant/app/node_modules/ng2-redux/lib/utils
```

The app still works. To avoid the warnings it can be simply excluded.

```javascript
test: /\.js$/,
loader: 'source-map-loader',
exclude: [
  /node_modules\/ng2-redux/
]
```

Cheers,
Tobi

**Comment by e-schultz** [comment]
@TobiasKrogh thanks for letting us know. Wondering if including the src with the npm package might be useful though for development/debugging purposes.

**Comment by TobiasKrogh** [comment]
@e-schultz I basically just followed the default configuration for the source-map-loader. I am fairly new to webpack, angular2 and ng2-redux. Just wondered about the warnings. However excluding ng2-redux from this loader works fine from my point of view. Just wanted to let you know in case this has some other implications or others stumble upon it.

**Comment by justsayno** [comment]
How does one get rid of these warning when using `cheap-module-source-map`?

I have been using the config in this [starter kit](https://github.com/AngularClass/angular2-webpack-starter)

And adding the above mentioned to the `config/webpack.common.js` doesn't do the trick. These warnings are fine but then if I pass it onto another dev they might get worried!

**Comment by TobiasKrogh** [comment]
@justsayno I looked up the mentioned starter kit and it would seem they already do such excludes for node_modules in webpack.common.js (which is merged into webpack.dev.js) and webpack.test.js

Example from webpack.common.js
```
      {
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
          // these packages have problems with their sourcemaps
          helpers.root('node_modules/rxjs'),
          helpers.root('node_modules/@angular'),
        ]
      }
```

You should be able to add one entry in the exclude array like `helpers.root('node_modules/ng2-redux')`. I shortly tested that and I do not see any warnings. Same applies of course to the webpack.test.js.

Webpack seems to recommend using the include over the exclude when possible (see Example in https://webpack.github.io/docs/configuration.html#module-loaders). In general the include / exclude works by passing one condition or an array of conditions which in turn can be path references or regular expressions.

Hope this helps.

**Comment by justsayno** [comment]
Yeah I tried adding that line before I made my post.. I'm not sure why its not effecting the output tbh. My loader for that looks like this:

```
{
  test: /\.js$/,
  loader: 'source-map-loader',
  exclude: [
    // these packages have problems with their sourcemaps
    helpers.root('node_modules/rxjs'),
    helpers.root('node_modules/@angular'),
    helpers.root('node_modules/ng2-redux')
  ]
}
```

**Comment by alexthewilde** [comment]
@e-schultz this seems to be still an issue. Getting this error on a fresh install of ng2-redux via npm:

> client:90 ./~/ng2-redux/lib/ng-redux.module.js
Cannot find source file '../src/ng-redux.module.ts': Error: Can't resolve '../src/ng-redux.module.ts' in '../node_modules/ng2-redux/lib'
 @ ./~/ng2-redux/lib/index.js 8:24-52

I just checked and `src/` isn't included in the npm package, despite https://github.com/SethDavenport/ng2-redux/commit/3cc6a76a1298fb4cacbc180d18b47a3c4d8c7741.
