### ISSUE TITLE
 Error: Actions must be plain objects.

### ISSUE THREAD

**Issue by lanocturne** [angular-redux/ng2-redux#71]
A question about how to call angular service function on container.

When I try to call a "service map to redux" function on container, I get this error => 
```ts
EXCEPTION: Error: Actions must be plain objects. Use custom middleware for async actions. in [null]
```
code is like:
```ts
this.ngRedux.mapDispatchToTarget((dispatch)=> {
      return {
        fetchToday: ()=>dispatch(
          this._service.fetch()
        )
      };
    })(this);
this.fetchToday();
```

Service function code is simply as
```ts
return (dispatch, getState)=> {
      dispatch(FETCH_TODAY_ACTIVITIES);
    }
```
where FETCH_TODAY_ACTIVITIES is a string

**Comment by e-schultz** [comment]
Redux requires the final dispatched action to be a plain JSON object, and it also expected to have a type property. 

Would

```js

return (dispatch, getState)=> {
      dispatch({type: FETCH_TODAY_ACTIVITIES});
    }
```

Redux is pretty un-opinionated about how you structure your objects - the only 'required' thing is it's a JSON object with a type property.

**Comment by lanocturne** [comment]
Great help! Many thanks.
2016年5月2日 下午7:19，"Evan Schultz" <notifications@github.com>写道：

**Comment by e-schultz** [comment]
@lanocturne happy to help. Going to close this issue, but if you have any other questions feel free to ask.

Thanks,

Evan

**Comment by lanocturne** [comment]
@e-schultz 
Probably you should update the README cook book code
```ts
loginUser(credentials) {
    return (dispatch, getState) => {
      **dispatch(LOGIN_USER_PENDING); **
...
```
to
```ts
dispatch({**type**: LOGIN_USER_PENDING}); 
```

**Comment by e-schultz** [comment]
@lanocturne good point - will update the readme. Thanks for the input/feedback.
