### ISSUE TITLE
Incorporating decorator to automate subscribe/unsubscribe ngRedux.connect

### ISSUE THREAD

**Issue by dfbaskin** [angular-redux/ng2-redux#82]
I had created a decorator that allowed a component to automatically subscribe and unsubscribe from the Redux application store on the Angular2 life cycle hooks.

[https://github.com/ng-cookbook/angular2-redux-complex-ui/blob/master/src/app/decorators/app-store-subscriber.ts](https://github.com/ng-cookbook/angular2-redux-complex-ui/blob/master/src/app/decorators/app-store-subscriber.ts)

Would it make sense to incorporate a similar directive into this library (using the ngRedux.connect method)?

**Comment by kosz** [comment]
Hi @dfbaskin, 

we have something similar in the works and pending approval. please see https://github.com/angular-redux/ng2-redux/pull/83 for a preview

**Comment by dfbaskin** [comment]
Thanks!
